### PR TITLE
Documentation for new course asset CDN capabilities.

### PR DESCRIPTION
**Pull request by tobz**
This is all about the upcoming support for being able to use a CDN for course assets and how to configure the LMS for it.

### CODE REVIEW

**Comment by lamagnifica** [comment]
## [DOC-2572](https://openedx.atlassian.net/browse/DOC-2572)

@tobz I am so sorry this got dropped. I hope you don't mind, but in the interests of making up for lost time I did a quick copy edit directly in your branch. Please review to make sure I didn't introduce any errrors or inaccuracies, and we'll get this merged ASAP.

### Reviewers

Possible roles follow. PR submitter checks the boxes after each reviewer finishes and gives :+1:. 
- [x] Subject matter expert: @tobz 
- [ ] Subject matter expert: 
- [x] Doc team review (sanity check): @pdesjardins 
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing
- [x] Ran ./run_tests.sh without warnings or errors

### Post-review
- [x] Add description to release notes task as a comment (doc addition)
- [ ] Add description to Eucalyptus release notes 
- [ ] Squash commits

**Comment by tobz** [comment]
LGTM. 👍

**Comment by pdesjardins** [comment]
This is an example of clear and well designed technical communication. Enthusiastic 👍 .

Unfortunately @tobz, it also means you're hired.

**Comment by lamagnifica** [comment]
hooray! thank you both, and apologies again @tobz . Welcome to the team!

**Pull request merged**
