### PR TITLE
Fix CSS so that mixed lists are displayed properly.

### PR DESCRIPTION
**Pull request by nedbat**
Also fix the page that started us down this path.

### CODE REVIEW

**Comment by nedbat** [comment]
@lamagnifica fixed. @talbs ok?

**Comment by lamagnifica** [comment]
Yay! :dancer: :+1:

**Comment by nedbat** [comment]
@mhoeber when you're ok with it, I'll merge.

**Comment by mhoeber** [comment]
:+1:  Thanks!

**Comment by talbs** [comment]
Sweet selector syntax, @nedbat.

:+1:

**Pull request merged**
