### PR TITLE
Upgrade sphinx to 1.6.5, and fix its warnings

### PR DESCRIPTION
**Pull request by nedbat**
## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

Upgraded Sphinx to 1.6.5.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by srpearce** [comment]
👍  AFAIK

**Comment by nedbat** [comment]
"AFAIK" A ringing endorsement indeed! :)  I can make a branch build on RTD to take a quick look.

**Comment by nedbat** [comment]
Hmm, I'm not sure I can make a branch build.  The nedbat/sphinx-165 branch doesn't appear in the versions page of the Research Guide (which is the book with the changed .rst files): https://readthedocs.org/projects/devdata/versions/

**Comment by srpearce** [comment]
@nedbat (cc: @edx/doc) I'm not sure what a branch build is/how to create a branch build or what to do next. Do you need information from the doc team?

**Comment by nedbat** [comment]
I made this draft build: http://draft-research-guide-sphinx-165.readthedocs.io/en/latest/index.html

It looks identical to the existing book as near as I can tell.  I'm going to go ahead and merge this.

**Pull request merged**
