### PR TITLE
[DOC-4013] suggest to keep logical commits in PRs instead of squashing them

### PR DESCRIPTION
**Pull request by singuliere**
## [DOC-4013](https://openedx.atlassian.net/browse/DOC-4013)

For non-trivial pull requests a single commit may be very difficult to
read. It can even be more difficult when coming back months later and
trying to understand how the pull request introduced a bug or a
regression.

The developer guide already suggests a pull request should be nicely
organized in logical commits. But it is not clear about squashing them
together, only suggesting it is a good practice but not explaining
why.

Clarify the benefits of keeping a well organized commit series in the
pull request. Add a hint for the person in charge of merging about how
to squash when merging without discarding the commit series.

Add a description of your changes with links to any relevant material.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [x] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @singuliere! I've created [OSPR-3114](https://openedx.atlassian.net/browse/OSPR-3114) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@singuliere Thank you for your contribution. @grantgoodmanedX Can you give this a look? Also, do you think someone from dev should also review?

**Comment by grantgoodmanedX** [comment]
@natabene Yes, somebody from dev should review, since this would be a policy change and I don't have the expertise to know if it's a good idea.

**Review by grantgoodmanedX — APPROVED** [review]
👍  This looks fine from a documentation point of view.

**Comment by natabene** [comment]
@nedbat Can you review this?

**Review by nedbat — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@singuliere 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1803&entry.1484655318=https://github.com/singuliere&entry.752974735=2019-02-22+10:01&entry.1917517419=2019-02-25+20:48&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by singuliere** [comment]
@nedbat that was fast, thanks :-)

**Pull request merged**
