### PR TITLE
Fixed url

### PR DESCRIPTION
**Pull request by cecilyhunt**

### CODE REVIEW

**Comment by mhoeber** [comment]
Hi @cecilyhunt.  Thank you for contributing to edX documentation.  Your work is welcome and appreciated.

Before we can merge your pull request, we need you to fill out the contributor's agreement:  http://edx.readthedocs.org/projects/edx-partner-course-staff/en/latest/

If you can scan it you can email it to me at hoeber@edx.org.

Thanks
Mark

**Comment by cecilyhunt** [comment]
Hi @mhoeber. I just sent you the completed contributor's agreement.
Cecily

**Comment by mhoeber** [comment]
@cecilyhunt   thank you.  I will merge this now.  I will also add you to the authors file.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @cecilyhunt! I've created [OSPR-5351](https://openedx.atlassian.net/browse/OSPR-5351) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by nedbat** [comment]
Hi, sorry for the new comment on this old pull request.  We're testing out re-scanning contributions, and our bot added a confusing message that you can ignore.  We'll fix that. Sorry about the noise.

**Pull request merged**
