### PR TITLE
typo in create_or_update_site table for ecommerce-secret

### PR DESCRIPTION
**Pull request by sboday**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @sboday! I've created [OSPR-1250](https://openedx.atlassian.net/browse/OSPR-1250) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by nedbat** [comment]
@sboday thanks for the usual attention to detail!  Once you send in the contributor agreement, we can merge this in.  I know it seems like a lot of paperwork for typo fixes, but I suspect we'll be seeing more from you in the future in any case.

**Comment by sboday** [comment]
Thanks Ned.  Just downloaded the form.  It will be next week before I can
sign.

**Comment by nedbat** [comment]
@sboday Thanks for the signed agreement.
@mulby this should be a quick review.

**Comment by mulby** [comment]
@nedbat this looks like ecomm stuff, did you mean @clintonb?

**Comment by clintonb** [comment]
👍

**Pull request merged**
