### PR TITLE
Remove note about optional tags on review comments.

### PR DESCRIPTION
**Pull request by cahrens**
Per the discussion begun by @mikigoyal, remove the optional nature of tags on PR review comments.

@dan-f and @mhoeber Please review

### CODE REVIEW

**Comment by dan-f** [comment]
:+1:

**Comment by mhoeber** [comment]
:+1:    @sarina   should confirm as this is primarily meant for open source contributors.

**Comment by cahrens** [comment]
@sarina are you OK with this? It was requested by Miki.

**Comment by sarina** [comment]
:+1:

**Pull request merged**
