### PR TITLE
edX Sphinx Theme

### PR DESCRIPTION
**Pull request by mhoeber**

### CODE REVIEW

**Comment by mhoeber** [comment]
@lamagnifica @catong @srpearce 

CC:  @talbs @frrrances @marcotuts @andywaldrop  @dporter-edx 

This is the start of publishing through RTD with an edX theme:  http://draft-theme-testing.readthedocs.org/en/latest/

Compare to existing:  http://edx.readthedocs.org/projects/edx-partner-course-staff/en/latest/

What I've done:
- Changed top left block to have edX logo, and changed background to fit it.
- Made table cell text wrap
- Tweaked block spacing on lists (will do some more tweaking in numbered lists)
- Changed some hardcoded text (e.g., Table of Contents in breadcrumbs instead of Doc, search box text)

Next Steps:
- Everyone can review, add change suggestions to this PR.  Please add comments before 1/5/15
- In comments, distinguish between things we must change before using this theme, and what we could enhance longer term.
- Up until 1/9/15, I will continue tweaking theme based on comments.
- Sprint starting 1/13/15, I will update config of existing products to use the theme and republish them.

**Comment by catong** [comment]
Some initial thoughts: 
- I find that the line spacing between bullet list items is too much. It looks especially odd on the TOC page.
- Tables look great! 
- I'm not very keen on the very dark blocks for Notes, Warnings, etc. but that's a personal preference. However, it does look as if there is a dark line on the left edge of these notes and warning blocks that perhaps can be removed?

**Comment by catong** [comment]
Spacing after the last list item and before the next regular paragraph still looks too much. For example, see the last line just before 6.3.7.

**Comment by catong** [comment]
There could be more spacing after images. For example, see 6.3.8 Step 1.

**Comment by lamagnifica** [comment]
The table formatting makes me weep with joy. Overall, I think this is sooo much better.
- Sylvia will be glad to see that the thumbnails appear correctly in Chrome here: http://draft-theme-testing.readthedocs.org/en/latest/exercises_tools/create_exercises_and_tools.html#general-exercises-and-tools
- I agree with Carol's comment about the way Notes are formatted -- a distracting amount of dark space around the text.
- Bullets do seem to have some quirks, esp. wrt the way TOC pages appear, and the inconsistent amount of space after the last bullet
  Hooray, @mhoeber !

**Comment by srpearce** [comment]
It would be great if all links looked the same instead of some of them appearing in italics and some appearing in Roman - see [6.6 Developing Course Components](http://draft-theme-testing.readthedocs.org/en/latest/developing_course/course_components.html) for an example of a list of Roman links followed by a list of italicized links, with more italicized links in [6.6.2 Add a Component](http://draft-theme-testing.readthedocs.org/en/latest/developing_course/course_components.html#add-a-component). The difference appears to be whether the link goes to an h1 or h2, or whether it's inline text made into a link.

**Comment by srpearce** [comment]
In tables, new paragraphs begin on new lines, but there's no white space between the two paragraphs (see [7.2.5.1 Advanced Options](http://draft-theme-testing.readthedocs.org/en/latest/creating_content/create_video.html#advanced-options)). Also, it looks like the font size is different in different cells of this table.

I think there's a little too much space between items in numbered lists - I don't think the spacing needs to be the same as the spacing between paragraphs. Inside a numbered list item, the spacing before and after an image looks good to me (see the space before and after the image in step 2, "In the Discussion component that appears, click Edit," in [7.3.2. Create a Discussion Component](http://draft-theme-testing.readthedocs.org/en/latest/creating_content/create_discussion.html#create-a-discussion-component)).

If a numbered list item contains text, an image, and then more text, there's more space between the first text block and the image than between the image and the second text block (see step 3, "When the Discussion component editor opens," in [7.3.2. Create a Discussion Component](http://draft-theme-testing.readthedocs.org/en/latest/creating_content/create_discussion.html#create-a-discussion-component)).

I also notice that items in bold and italics seem to be in a larger font than the rest of the paragraph - for example, in the text after the warning block in [7.3.2. Create a Discussion Component](http://draft-theme-testing.readthedocs.org/en/latest/creating_content/create_discussion.html#create-a-discussion-component), the word "categories" in italics seems larger than the other text, and the bold "Discussion" does as well. (I seem to recall that there was a problem with italics for the font that we're using - that the font itself doesn't have an italic version, so something else was being substituted? It might not be a big enough deal to look into right now, though.)

**Comment by mhoeber** [comment]
@catong @lamagnifica @srpearce   I've addressed Carol and Alison's comments.  Will work through Sylvia's by Monday.

http://draft-theme-testing.readthedocs.org/en/latest/index.html

**Comment by mhoeber** [comment]
@lamagnifica @catong @srpearce   believe I've address all notes:  http://draft-theme-testing.readthedocs.org/en/latest/

note we even have a favicon.

It would be really nice to merge this soon, then apply to all projects in next sprint!

**Comment by catong** [comment]
@mhoeber are we keeping the very dark Notes and Warnings blocks?

**Comment by lamagnifica** [comment]
:+1: Like Carol I preferred the two-toned coloring of the old Notes/Cautions, but think that can be altered in the future.

**Comment by mhoeber** [comment]
@catong @lamagnifica   I did not change any coloring of notes/warnings.  I shrank the amount of padding of the colored box around text.  Can you give example of change you mean, in this doc vs. the published one?

**Comment by mhoeber** [comment]
never mind, I see issue now, will try to restore the top bar color difference

**Comment by srpearce** [comment]
:+1: 

Question: What's a favicon?

**Comment by catong** [comment]
@mhoeber I just noticed that the unexpected notes/warnings etc. formatting change seems to be more than the top/bottom bar difference. "Important" and "Note" are now the same color?
See 12.11.2.1, for example.
BEFORE: 
http://edx.readthedocs.org/projects/edx-partner-course-staff/en/latest/running_course/course_grades.html
AFTER:
http://draft-theme-testing.readthedocs.org/en/latest/running_course/course_grades.html#generate-grades-for-enrolled-students-all-courses

**Comment by catong** [comment]
Looks great! :+1: other than the notes formatting troubleshooting, but that's not a showstopper

**Comment by mhoeber** [comment]
Regarding notes/warnings/important -- this is a pain.  the two-tone code you see on RTD, you actually don't see when you build locally.  It's a RTD feature, not part of the theme.  Now that we're overriding the RTD theme, the two-tones goes away.   So it'll be a good piece of work to enhance the presentation of these types.  I'm inclined to merge this, have followup stories for this (and many other nice to haves) in the future.

**Comment by mhoeber** [comment]
OK, toned down notes and warnings.  no two-tone.  enhancements for another day.

http://draft-theme-testing.readthedocs.org/en/latest/index.html

**Pull request merged**
