### PR TITLE
DOC-2372/TNL-3697

### PR DESCRIPTION
**Pull request by catong**
Make note about course team member enrollment clearer. (TNL-3697, DOC-2372)
@explorerleslie @lamagnifica please review. I would like to get this small change merged as soon as possible.

### CODE REVIEW

**Comment by explorerleslie** [comment]
:+1:

**Comment by lamagnifica** [comment]
:+1: I have a PR that involves the file that describes adding team members in Studio. I'll add the same note there.

**Comment by catong** [comment]
Thanks @lamagnifica FYI the template change PR for the same JIRA ticket: https://github.com/edx/edx-platform/pull/10379. I've tagged you for review there too.

**Comment by catong** [comment]
Merging https://github.com/edx/edx-documentation/pull/647

**Pull request merged**
