### PR TITLE
DOC: B&R Guide restructuring 1

### PR DESCRIPTION
**Pull request by catong**
DOC-2430: Create "set up course" folder, move files, modify index files

The first of many steps in restructuring the B&R Course Guide.

@lamagnifica or @srpearce please do sanity check/test only for structure integrity -- there will be more detailed updates later to tweak content. Not all chunks of content in a PR will be where they will end up at the end of the restructuring; moves are being done in chunks that can be successfully built locally.

### CODE REVIEW

**Comment by lamagnifica** [comment]
built clean, both guides, using the run_tests.sh script
:+1:

**Comment by lamagnifica** [comment]
:dancer:

**Comment by catong** [comment]
@lamagnifica Oopsie: it's my 2nd commit (post your thumbs) that adds the COMPLETE set of equivalent changes to the open edx folders. Run_tests.sh ran clean for me as well after the 2nd commit, but I'd love verification from you also.

**Comment by lamagnifica** [comment]
looks good :+1:

**Comment by catong** [comment]
Merging https://github.com/edx/edx-documentation/pull/689

**Pull request merged**
