### PR TITLE
changes Hawthorn to Ironwood in upgrade section

### PR DESCRIPTION
**Pull request by chintanjoshi1**
## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

In Upgrade section docs said to make a fresh installation of Hawthorn release instead of Ironwood.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @chintanjoshi1! I've created [OSPR-3301](https://openedx.atlassian.net/browse/OSPR-3301) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by openedx-webhooks** [comment]
@chintanjoshi1 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1815&entry.1484655318=https://github.com/chintanjoshi1&entry.752974735=2019-04-10+06:50&entry.1917517419=2019-04-10+11:51&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by natabene** [comment]
@chintanjoshi1 Hi, if you have already signed a contributor's agreement with us using a different Github username, please let me know. Without this we, unfortunately, cannot take your contributions.

**Comment by chintanjoshi1** [comment]
@natabene I have signed agreement, under [ichintanjoshi](https://github.com/ichintanjoshi)

I am sorry for using the wrong id, do I need to submit the PR from that account or is it fine ?

**Comment by natabene** [comment]
@chintanjoshi1 That is fine, we can use both, but please confirm your new Github username from your other account, e.g. by commenting and confirming in this PR, or using email that you indicated when signing agreement. Thanks.

**Comment by ichintanjoshi** [comment]
@natabene Hi, please pardon me (@chintanjoshi1 ) for using the wrong account.
I hereby confirm that @chintanjoshi1 is my account. 

Again sorry for the trouble. It was a single word change and I didn't notice the account I was using.

**Comment by natabene** [comment]
> @natabene Hi, please pardon me (@chintanjoshi1 ) for using the wrong account.
> I hereby confirm that @chintanjoshi1 is my account.
> 
> Again sorry for the trouble. It was a single word change and I didn't notice the account I was using.

Thank you, you are all set to contribute from either account.

**Pull request merged**
