### PR TITLE
Adds the pull request template for documentation contributions

### PR DESCRIPTION
**Pull request by lamagnifica**
@catong @pdesjardins @srpearce 
I followed the instructions that Cale pointed me to and added our template back. https://help.github.com/articles/creating-an-issue-template-for-your-repository/ 

FYI @jbarciauskas @cpennington

### CODE REVIEW

**Comment by pdesjardins** [comment]
Great! I thought everyone else was seeing a PR template automatically applied and that my GitHub account was misconfigured. 👍 👍 👍

**Comment by lamagnifica** [comment]
Nope, it went missing some weeks ago for everyone... apprarently, at some point they decided to change how it was implemented (to this procedure) and dismantled the way it was implemented previously. Somehow, the "how to do it right" didn't get passed on to us, at least.

**Comment by cpennington** [comment]
Mea culpa. Sorry for not passing on the info to those of you who were using the other template style. You might want to get rid of the old template, while you're at it.

**Comment by srpearce** [comment]
💯

**Comment by lamagnifica** [comment]
no prob, Cale, glad we started asking "what happened?" 
I searched the repo for "template" and see several instances in which we mention the existence of the template, but no file... where was it added before?

**Comment by lamagnifica** [comment]
oh, wait, @cpennington is it 
https://github.com/edx/edx-documentation/blob/master/.pr_cover_letter.md.j2
?

**Comment by cpennington** [comment]
Yeah, that's the one.

**Pull request merged**
