### PR TITLE
Hack and slash dev guide

### PR DESCRIPTION
**Pull request by sarina**
Hackathon: Remove old/useless parts of the dev guide and update various parts of the new guide (see https://docs.google.com/document/d/1QQKDStH6OFSPH2NSt5j9XVUayVSwkZs12L-McUbPjeo/edit?usp=sharing )

@feanil @brian-smith-tcril @arbrandes @cintnguyen

### CODE REVIEW

**Comment by sarina** [comment]
@feanil I think this is ready to go. My proposal is we should merge this in, migrate the pages, then work on further improvements. Thoughts?

**Comment by sarina** [comment]
@feanil I think you committed your xss fix to master, but not the fix that I think I dropped in conflict resolution thinking you had fully committed the xss stuff to master. Could you apply your fix again?

**Comment by sarina** [comment]
@feanil since we migrated this in https://github.com/openedx/docs.openedx.org/pull/361 to docs.openedx.org, should we just pull this content out of the legacy site?

**Comment by feanil** [comment]
Yea, I think the legacy site should just be a link to the new location or ideally a redirect to the no location with no content in the `edx-documentation` repo.

**Pull request merged**
