### PR TITLE
Peer instruction for learners

### PR DESCRIPTION
**Pull request by lamagnifica**
## [DOC-2287](https://openedx.atlassian.net/browse/DOC-2287)

Adds a description of how to complete this assignment type for learners.
Apologies, reviewers, for all the noise in this PR, I'm obviously trying to do too many things at once. The interesting commit is https://github.com/edx/edx-documentation/commit/47b45cc43688bc5f8050ef620284d42376676043 and the most interesting file is interactive_multiple_choice.rst
### Reviewers
- [x] Subject matter expert:  @xcompass
- [ ] Subject matter expert: 
- [ ] Doc team review (dev edit): @catong 
- [x] Product review: @explorerleslie 

Please tag others as desired.
FYI: @cptvitamin @bradenmacdonald 
### Testing
- [x] Ran ./run_tests.sh without warnings or errors
### Post-review
- [x] Add description to release notes task as a comment
- [x] Squash commits

### CODE REVIEW

**Comment by lamagnifica** [comment]
I set up a draft HTML file:
http://draft-20160120-pi-for-learners.readthedocs.org/en/latest/completing_assignments/interactive_multiple_choice.html

**Comment by explorerleslie** [comment]
I only had time for a quick review, but looks good. :+1:

**Comment by xcompass** [comment]
@lamagnifica PI parts looks good. I'm double checking with Letitia about the license of the dog pictures. Will keep you posted.

**Comment by lamagnifica** [comment]
ah, terrific @xcompass I wasn't sure if the example would be ok to use but it was a great starting point!

**Pull request merged**
