### PR TITLE
Adds encouragement to use display names. Replaces PR 90

### PR DESCRIPTION
**Pull request by lamagnifica**

### CODE REVIEW

**Comment by lamagnifica** [comment]
@mhoeber I had to jettison my original (months old) PR. Thumbs up from everyone involved weeks ago. When I tried to squash today, there were just too many github problems and merge conflicts, which would only get reported 6 at a time (I'd fix 6, wait for tests, and get a list of 6 new conflicts, repeated several times). This PR duplicates the essentials, adds two images that Sylvia forgot to add last week, and though the travis builds continue to fail the failures are not for anything introduced by this PR.

**Comment by mhoeber** [comment]
Looks good.  Can you check this build error:  

../shared/exercises_tools/numerical_input.rst:69: ERROR: Error in "image" directive:
no content permitted.
.. image:: ../../../shared/building_and_running_chapters/Images/ProbCompButton_NumInput.png
    :alt: Image of the numerical input button

**Comment by lamagnifica** [comment]
I checked it up down and sideways. I deleted it, added it back, completely retyped the image link, and it still fails. How much more time should I spend on this?

**Comment by mhoeber** [comment]
don't worry about it then.  i'm looking into it

**Comment by lamagnifica** [comment]
@mhoeber I'm looking at that chapter now. I think that if we delete that image (of an icon on the simple editor toolbar) completely and make a very minor change to the wording we'll be ahead of the game. Ok to pull the trigger on that?

**Comment by mhoeber** [comment]
I wasn't getting that warning on the project I just merged.  so should be ok with a rebase, I think

**Pull request merged**
