### PR TITLE
updates updates & handouts image

### PR DESCRIPTION
**Pull request by lamagnifica**
## [DOC-3162](https://openedx.atlassian.net/browse/DOC-3162)

We missed a screen shot when the tabs got renamed...
### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 
- [x] Subject matter expert: @jaakana
- [ ] Subject matter expert: @indagation
- [x] Doc team review (sanity check): @catong @pdesjardins @srpearce
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 
### Testing
- [x] Ran ./run_tests.sh without warnings or errors
### Post-review
- [x] Squash commits

### CODE REVIEW

**Comment by pdesjardins** [comment]
Looks right to me. 👍

**Comment by JAAkana** [comment]
Looks good, and I dig the highlights! (:palm_tree:)

**Comment by indagation** [comment]
Looks good to me. It is good that it includes the Important Course Dates as well.

**Comment by lamagnifica** [comment]
:)

**Pull request merged**
