### PR TITLE
WIP: Reference `eucalyptus.2` tag instead of 1

### PR DESCRIPTION
**Pull request by gsong**
**WIP: Do no merge yet**

Refer to `eucalyptus.2` instead of `eucalyptus.1`.
### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 
- [ ] Subject matter expert: @nedbat
- [x] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
### Testing
- [x] Ran ./run_tests.sh without warnings or errors
### Post-review
- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by lamagnifica** [comment]
@gsong that all looks fine to me. 👍  Something to consider for the future, though, is revising the way we present this information so that readers will go and find the most recent release version, rather than relying on us to update in in multiple places in multiple files?

**Comment by nedbat** [comment]
We already have "For information about the latest Open edX releases and the Git tag names for them, see `Open edX Releases Wiki page`_."

I agree that we should not be updating this text for every release.  To that end, it might be best to make clear that the examples are fictitious. In other places, I've used "zebrawood.3" so that people won't be distracted by the "eucalyptus" word.

**Comment by gsong** [comment]
@nedbat For those that just copy and paste, I wanted to make sure they get the latest release instead of an older release.

Shall we just close this PR then?

**Comment by nedbat** [comment]
I intended "eucalyptus.1" to be an example, though it was a poor choice, since it was also the current release at the time.  What would make a clearer example?

**Comment by catong** [comment]
@gsong What is the next step for this PR?

**Comment by gsong** [comment]
@catong Haven't had a chance to come back to this. Can we leave it as WIP for now?

**Comment by catong** [comment]
@gsong No problem! We are just checking on what might be inactive PRs. Thanks!

**Comment by grantgoodmanedX** [comment]
We don't want to update the version with each release. Since it's just an example string, I like @nedbat 's tentative suggestion that we go with something like 'zebrawood.3'. I'd also be ok with just closing this PR, since there's nothing in the doc that's false, and the farther we get from eucalyptus.1, the less likely it is that a user will just cut and paste the example commands.

**Comment by nedbat** [comment]
How about "examplewood.1" ? :)

**Comment by gsong** [comment]
Since this hasn't been an issue, I'll just close out the PR.

**Pull request closed without merging**
