### PR TITLE
Added edX101 to preface

### PR DESCRIPTION
**Pull request by lamagnifica**
@srpearce , @mhoeber , @catong figured I'd add this to the preface too.

### CODE REVIEW

**Comment by mhoeber** [comment]
:+1:   lets get in RN next week too

**Comment by srpearce** [comment]
Do you want to include a link to DemoX too?

**Comment by lamagnifica** [comment]
added to release notes task, @mhoeber 
DemoX is already described in the preface, @srpearce

**Comment by lamagnifica** [comment]
merging based on @mhoeber's feedback

**Pull request merged**
