### PR TITLE
Make Travis fail builds on warnings.

### PR DESCRIPTION
**Pull request by nedbat**
I also fixed the two existing image reference warnings.

### CODE REVIEW

**Comment by nedbat** [comment]
@lamagnifica @catong @srpearce @pdesjardins This changes Travis to fail (red X) if there are any warnings or errors at all.  Previously, Travis would give you a red X on errors, but warnings were allowed.
@clytwynec in case I did this sub-optimally, advice welcome.

**Comment by catong** [comment]
@nedbat the image paths fix look good; thanks for taking care of them! :+1: for that; I can't comment on the test fix, except that I agree with the wording change.

**Comment by nedbat** [comment]
@catong (et al.) On the script itself, I need your OK with the process change, since you will be living with the results of this more than I will.

**Comment by catong** [comment]
@nedbat The process change is fine with me; I agree that we need the Travis test to show as Failed not just when there are errors, but also when there are warnings. Thanks!

**Comment by lamagnifica** [comment]
local tests run without error after these changes. 
:+1:

**Pull request merged**
