### PR TITLE
Fixes DOC-1330

### PR DESCRIPTION
**Pull request by lamagnifica**
@mmacfarlane , @WatsonEmily : this addresses a request for clarification about beta testers and certificates
@catong , @srpearce , @mhoeber FYI, backlog item, no schedule.

### CODE REVIEW

**Comment by WatsonEmily** [comment]
@jhendersonedx - please review. Thanks.

**Comment by lamagnifica** [comment]
Revised per @jhendersonedx's comment

**Comment by lamagnifica** [comment]
@jhendersonedx, @catong, @srpearce, @mhoeber, just pinging you to make sure this review is on your radar...

**Comment by srpearce** [comment]
:+1:

**Pull request merged**
