### PR TITLE
Delete unused edx-documentation subdirectories

### LINKED ISSUE #2008: Clean up content in the edx-documentation repo that is not being referenced by anyone.
There are RST files in the edx-documentation repo that don't seem to be published anywhere.

Stakeholders: Marco Morales, Jennifer Akana, Ben Piscopo, @nedbat 

AC:
- Any unused RST files in the edx-documentation repo have been removed.

### PR DESCRIPTION
**Pull request by Carlos-Muniz**
Closes #2008 

Open edX and edX documentation is splitting. In order to make this process easier, we are deleting unused edx-documentation subdirectories, and any mentions of content in these subdirectories. The following subdirectories are being deleted with this PR.

- release_notes_2014
- release_notes
- user_retirement
- ORA2
- students

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:.

- [ ] Subject matter expert:
- [ ] Subject matter expert:
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support:
- [ ] PM review:

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [X] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [x] Squash commits

### CODE REVIEW

**Review by feanil — COMMENTED** [review]
Generally looks good to me, looks like there is an issue in the `en_us/open_edx_release_notes` that needs to be fixed before this is ready to go but other than that, it think we can probably land this shortly.

**Comment by Carlos-Muniz** [comment]
fixed the warning related to the missing reference in `en_us/open_edx_release_notes`

**Comment by Carlos-Muniz** [comment]
`students_redirect` has been un-deleted.

**Review by feanil — APPROVED** [review]

**Comment by Carlos-Muniz** [comment]
Update: I finally got this all to pass, though it's a hack, and I don't think it's the right way to proceed. It seems like the tests were failing because the site `edx-guide-for-students` has been taken off RTD. The `intersphinx_mapping` fall back was to use the `students` subdir. With both of those gone, links in other subdirs that we are keeping, were failing. I switched the `intersphinx_mapping` to instead point to `student_redirect`, which we will also not be keeping in the longterm.

**Comment by Carlos-Muniz** [comment]
I think the right solution is to move all necessary content from student to shared/student, and use it from there. But I'm not sure how that will work.

**Review by feanil — APPROVED** [review]
It's a bit messy but we can always make it better later since we'll be continuing to spend time with the docs.

**Pull request merged**
