### PR TITLE
Fix broken links 

### PR DESCRIPTION
**Pull request by ghassanmas**
## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

This PR is intended to fix external or internal links that are checked using `make linkcheck` for each direactory, to generate the report for links. 
For example generate linkcheck report for  `install_operation` 
 ```
 cd en_us/install_operations
 make linkcheck
 ```
The above will generate a file in the build directoy, as `en_us/install_operations/build/linkcheck/output.txt`, the broken links are found in that file, here is an example output for the first broken link: 

> `11 configuration/youtube_api.rst:52: [broken] http://docs.ansible.com/ansible/index.html: 404 Client Error: Not Found for url: https://docs.ansible.com/ansible/index.html` 

This PR relates to #1972 , thogh the title of the issue is not relavnt anymore 

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Testing
In order to test that the changes have fixed broken links, one could compare the output of `linkcheck` as follows: 

First run linkcheck form master in in `en_us/install_operations` directory;

1. `git checkout master`
2. `cd en_us/install_operations`
3. `make linkcheck -j 4` (this will generate the `build/linkcheck/output.txt` file)
4. `grep -c 'broken' build/linkcheck/output.txt` (this will count broken links) e.g. *30*
5. `git checkout `fix-broken-links`
6. `make linkcheck -j 4` (now this will overide the `build/linkcheck/output.txt` file from step 3) 
7. `grep -c 'broken' build/linkcheck/output.txt` (compare the result from step 4) e.g. *26*

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ghassanmas! I've created [OSPR-5999](https://openedx.atlassian.net/browse/OSPR-5999) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by nedbat** [comment]
@ghassanmas are you still working on this?

**Comment by ghassanmas** [comment]
@nedbat There are still some links that needs to be fixed, if it possible to submit another PR later for other fixes, then I guess it would make sense to merge sense.

**Comment by nedbat** [comment]
@ghassanmas oops, sorry this sat a long time. If you are ready to go, click "Ready for review" to take this PR out of draft status.

**Comment by ghassanmas** [comment]
@nedbat done, I have wrapped them into a single commit that fixes 4 links.

**Comment by openedx-webhooks** [comment]
@ghassanmas 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-documentation&entry.867055334=https://github.com/openedx/edx-documentation/pull/1977&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2021-08-28+11:15&entry.1917517419=2022-01-13+21:49&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
