### PR TITLE
Adds Details about Adding Course Mode to Enable Certificates for a Course

### PR DESCRIPTION
**Pull request by nizarmah**
When trying to add a Course Certificate, I was having trouble. Apparently, the documentation is missing the necessary information about adding a "Course Mode" in order to enable Certificates for a course.

This PR adds the following information to the documentation:
- **Certificate Web/HTML View Enabled** is a deprecated settings
- **Certificate Web/HTML View Enabled** is now enabled by default
- **Course Mode** is necessary to enable Course Certificates
- **Course Mode** has different certificate types, mentioned in **enrollment_track**

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] @toxinu
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc

### Testing

- [x] Ran `./run_tests.sh en_us/open_edx_course_authors`
- [x] Built the changes locally using `./develop.sh en_us/open_edx_course_authors` and navigated to the following page:
```
http://127.0.0.1:9090/set_up_course/studio_add_course_information/studio_creating_certificates.html
```

> `./run_tests.sh` resulted in warnings but not related to the changes that I made

### Screenshot of Changes

image

[Here is a link to that section, prior to the changes.](https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/set_up_course/studio_add_course_information/studio_creating_certificates.html#enable-certificates)

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @nizarmah! I've created [OSPR-4910](https://openedx.atlassian.net/browse/OSPR-4910) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by toxinu** [comment]
@nizarmah It looks good to merge 👍🏻 

- [x] I built the documentation and checked the changes

**Comment by natabene** [comment]
@nizarmah Thank you for your contribution. @nedbat Do you want to give this a look?

**Comment by openedx-webhooks** [comment]
@nizarmah 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1882&entry.1484655318=https://github.com/nizarmah&entry.752974735=2020-08-19+14:00&entry.1917517419=2020-08-22+12:01&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
