### PR TITLE
Fixes DOC-2670

### PR DESCRIPTION
**Pull request by lamagnifica**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
## [DOC-2670](https://openedx.atlassian.net/browse/DOC-2670)

@clrux is hard at work making H1's and H2's accessible. See the description in the doc story and 
https://github.com/edx/edx-platform/pull/11247

### Date Needed

Releasing 9 Feb 2015

### Reviewers
- [x] Subject matter expert: @clrux 
- [x] Doc team review (sanity check): @pdesjardins 

### Testing
- [x] Ran ./run_tests.sh without warnings or errors

### Post-review
- [x] Add description to release notes task as a comment
- [x] Squash commits

**Comment by pdesjardins** [comment]
These changes look sane, and good, to me. :+1:

**Comment by pdesjardins** [comment]
These changes look sane, and good, to me. :+1:

**Comment by downzer0** [comment]
I had one suggestion/question. Otherwise :+1:

**Pull request merged**
