### PR TITLE
Update XBlock tutorial details

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
@lamagnifica @pdesjardins @Lyla-Fischer look ok?

**Comment by lamagnifica** [comment]
@nedbat do you have a story or other info about this change that we can refer to? 
The doc team typically tests all changes by making an html version and we also add a change log entry for the affected guide(s), please let me know if you need us to do those things for you for this PR.

**Comment by Lyla-Fischer** [comment]
:+1: from my point of view. Thanks for the corrections.

**Comment by nedbat** [comment]
@lamagnifica I don't have a story.  These were things I noticed as I was working through a different PR.  I've added a Change Log entry, let me know how else to be a good citizen here.

**Comment by lamagnifica** [comment]
Thanks @nedbat I am building all guides from your branch now to make sure nothing breaks. Thumbs imminently, I'm sure!

**Comment by lamagnifica** [comment]
@nedbat I think you need to rebase, getting some errors when I build...

**Comment by nedbat** [comment]
I've rebased, but I didn't see any problems when I built locally before the rebase, and travis seems happy.  What are you seeing?

**Comment by lamagnifica** [comment]
@nedbat because we use includes and onlys to produce separate versions of the guides for open and partners, we needed a more comprehensive test strategy than just making a single guide. We now run a shell script to rebuild all of the guides and run it for all of our PRs before merging. Carol made some significant changes that went out concurrently with yesterday's release, so test still failed on your branch until you rebased. 
We use a template for our PRs that includes the shell script and other steps we complete: https://openedx.atlassian.net/wiki/display/DOC/Doc+Team+Pull+Request+Template

AND, tests just ran clean! :+1:

**Comment by nedbat** [comment]
OK, merged, thanks.  If PRs here should use that format, you might want to put it into the README.rst.

**Pull request merged**
