### PR TITLE
Revert "Partial Credit Update"

### PR DESCRIPTION
**Pull request by catong**
Reverts edx/edx-documentation#525
@explorerleslie @mhoeber

### CODE REVIEW

**Comment by catong** [comment]
@lamagnifica Can you please give thumbs to confirm?

**Comment by explorerleslie** [comment]
:+1:

**Comment by catong** [comment]
Merging https://github.com/edx/edx-documentation/pull/532 once tests pass

**Comment by lamagnifica** [comment]
thanks, @catong :+1:

**Pull request merged**
