### PR TITLE
(WIP) WL-504: Otto comprehensive theming wiki is added.

### PR DESCRIPTION
**Pull request by malikshahzad228**
## [WL-504](https://openedx.atlassian.net/browse/WL-504)

Documentation for Comprehensive Theming setup for Otto is added in wiki.
### Reviewers

@mattdrayer 
@saleem-latif 
### Testing
- [x] Ran ./run_tests.sh without warnings or errors
### Post-review
- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by mattdrayer** [comment]
@pdesjardins FYI -- Otto comprehensive theming is in master/production

**Comment by pdesjardins** [comment]
@mattdrayer This is a doc PR that's going directly into our published doc set. I thought the plan was to put this on a wiki page first. I can take this content and use it for my own research though. I don't think we should merge this right away.

About timing, does that fact that Otto theming is in master/production make theming doc more urgent? I'm still planning for a late July deadline for the doc.

**Comment by mattdrayer** [comment]
Hmm, okay -- I wasn't sure how the edx/ecommerce project fits into the named release paradigm.  We could leave this PR open until we are ready to publish the info, or close it and submit a new one down the road.  Either way, @malikshahzad228 perhaps we should publish the howto information on the edX wiki @ https://openedx.atlassian.net/wiki/display/FEDX/Comprehensive+Theming

@andy-armstrong thoughts?

**Comment by pdesjardins** [comment]
@malikshahzad228, thanks for adding this content to https://openedx.atlassian.net/wiki/display/SOL/Comprehensive+Theming. Let's close this documentation PR. I will update the theming instructions when I work on https://openedx.atlassian.net/browse/DOC-2636.

**Pull request closed without merging**
