### PR TITLE
chore: add ENABLE_COURSE_DISCOVERY_DEFAULT_LANGUAGE_FILTER flag

### PR DESCRIPTION
**Pull request by navinkarkera**
https://github.com/openedx/edx-platform/pull/33647

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:.

- [ ] Subject matter expert:
- [ ] Subject matter expert:
- [ ] Product review:
- [ ] Partner support:
- [ ] PM review:

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @navinkarkera! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @navinkarkera - is this ready for review?

**Comment by mphilbrick211** [comment]
@openedx/axim-engineering I think this is all set.

**Comment by feanil** [comment]
It looks like this is blocked on the code PR https://github.com/openedx/edx-platform/pull/33647 landing.  We shouldn't merge this until after that has merged.

**Comment by farhaanbukhsh** [comment]
@feanil The PRs are merged :)

**Comment by navinkarkera** [comment]
Closing, deemed unnecessary. See this [comment](https://github.com/openedx/edx-platform/pull/33647#issuecomment-1929408672)

**Pull request closed without merging**
