### PR TITLE
tpa_oauth.rst minor typo fixed 

### PR DESCRIPTION
**Pull request by CodeWithEmad**
fixed a couple of typos: 
```
commmon -> common
Create the new application -> Create a new application.
key value -> key-value
```

### Date 
March 6 2022

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:.

- [ ] Subject matter expert:
- [ ] Subject matter expert:
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support:
- [ ] PM review:

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @CodeWithEmad! I've created [OSPR-6505](https://openedx.atlassian.net/browse/OSPR-6505) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by natabene** [comment]
@CodeWithEmad 
Thank you for the contribution! Once you have signed our Contributor Agreement and it has been processed, you will receive a confirmation via email from our Legal team. We then will be able to review this and all your future code contributions.

**Comment by CodeWithEmad** [comment]
Glad to be a part of this @natabene. I'm waiting to hear from your legal team.

**Comment by natabene** [comment]
@CodeWithEmad Have you heard from our Legal team? Was you agreement processed?

**Comment by CodeWithEmad** [comment]
so sorry for the delay @natabene. I didn't have my laptop for the past 2 weeks. I was accepted as an edx contributor a couple of months ago, but never had the time to contribute to the project. is it possible for you or other people who manage the repository to link me with the legal department?

**Comment by natabene** [comment]
@CodeWithEmad Sure, I will do that.

**Comment by CodeWithEmad** [comment]
Appreciate it @natabene. I just filled another one of the contribution contract, in case they missed the last one. Hope to hear from them soon

**Comment by natabene** [comment]
@CodeWithEmad Thank you, you are all set now, and we can review your code.

**Comment by dianakhuang** [comment]
Hi @CodeWithEmad ! Thanks so much for this. It looks good overall, but it's failing on the commitlint check, because we use [conventional commits|https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html] for our commit messages. If you could update the commit message to use a prefix like `fix: `, then I can approve and merge this.

**Comment by CodeWithEmad** [comment]
Hi @dianakhuang! Happy to be a part of this. sure, I'll change it now.

**Comment by CodeWithEmad** [comment]
weird. I'm not sure why cla bot fails. I submitted the form and signed the document using DocuSign and received the approval email. can we figure this out for other pull requests in the future?

**Comment by dianakhuang** [comment]
@natabene do you have any way of checking why the CLA bot is failing?

**Comment by dianakhuang** [comment]
@CodeWithEmad I'm happy to merge this even if the CLA check fails, since @natabene has given her sign off on it.

**Comment by natabene** [comment]
let me fix it

**Comment by edx-webhook** [comment]
@CodeWithEmad Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-documentation&entry.867055334=https://github.com/openedx/edx-documentation/pull/2030&entry.1484655318=https://github.com/CodeWithEmad&entry.752974735=2022-03-06+13:27&entry.1917517419=2022-04-01+22:54&entry.2133058324=No) so we can improve your experience in the future.

**Comment by natabene** [comment]
I know what the problem is.  We will fix it early next week.

**Comment by CodeWithEmad** [comment]
Hi @natabene. I was wondering if I contribute to other repositories of openedx, this CLA bot blocks me again?

**Comment by natabene** [comment]
@CodeWithEmad Yes, this check will apply to any of the openedx repositories. So you can either wait till we fix it (apologies for a delay here!) or you can open PRs against other repos, and once the check clears here, it will also clear in other repos.

**Comment by dianakhuang** [comment]
Since the CLA has been signed, I'm going to merge this one now so it's not blocked on the fix to the CLA bot.

**Comment by openedx-webhooks** [comment]
@CodeWithEmad 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-documentation&entry.867055334=https://github.com/openedx/edx-documentation/pull/2030&entry.1484655318=https://github.com/CodeWithEmad&entry.752974735=2022-03-06+13:27&entry.1917517419=2022-04-06+14:06&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
