### PR TITLE
fix: handle error when conf.py is running by sphinx-intl

### PR DESCRIPTION
**Pull request by ghassanmas**
## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

Wrapped the statement which extracts the buidler from `sys.argv`, because when `sphinx-intl` runs `conf.py` is doesn't   have the `- b` arg. 

For more context about why `sphinx-intl` is being used, please refer to this [ticket](https://trello.com/c/q4JJOHeo/4-we-would-like-to-have-user-documentation-translated-into-the-10-languages-that-we-are-focusing-our-transifex-strategy-on-in-orde). 

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ghassanmas! I've created [OSPR-6088](https://openedx.atlassian.net/browse/OSPR-6088) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@ghassanmas Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by ghassanmas** [comment]
@natabene Yes it's  ready for review.

**Review by nedbat — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@ghassanmas 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1983&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2021-09-30+20:45&entry.1917517419=2021-10-20+19:52&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
