### PR TITLE
Reset all students just for admins

### PR DESCRIPTION
**Pull request by andersonresende**
That PR fix https://openedx.atlassian.net/browse/DOC-2406.
Moved "Reset ALL students' attempts" from staff to admin role.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @andersonresende! I've created [OSPR-943](https://openedx.atlassian.net/browse/OSPR-943) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by sarina** [comment]
Hi @andersonresende and thanks! Can you please follow the bot's instructions to submit a contributor's agreement?

Docs team - please don't merge until someone on the open source team has confirmed we have a contributor's agreement.

**Comment by andersonresende** [comment]
Hello @sarina I added my name to AUTHORS file. What else I need to do?

**Comment by sarina** [comment]
You must sign and send in the contributor's agreement, as I stated. Please
see the bot's comments.

**Comment by andersonresende** [comment]
Thanks @sarina I already send the email with my signature.

**Comment by andersonresende** [comment]
I already receive a confirmation about my contributor agreement. Please review my PR.

**Comment by catong** [comment]
:+1: Thanks for the fix!

**Comment by sarina** [comment]
Carol as with all OSPRs please merge the PR, or indicate next steps.

**Comment by catong** [comment]
Thanks @sarina. I'll squash commits and merge this PR.

**Comment by catong** [comment]
@sarina, I was going to merge this, but then realized the PR is not off the correct repository. How would you like to handle this? Thanks.

**Comment by sarina** [comment]
This is an open source pr. If the author needs to do something prior to
merge please indicate so.

**Comment by catong** [comment]
Hi @andersonresende The doc change should be made to the edx/edx-documentation repository. Can you please make a new PR against the correct repo? Thanks!

**Comment by andersonresende** [comment]
@catong Was made for wich repository?
I forked edx/edx-documentation and made a PR.

**Comment by sarina** [comment]
Carol open source contributors make prs from their own fork. Talk with me
or Alison in person to understand more fully what open source means.

**Comment by catong** [comment]
@andersonresende Apologies for the confusion. I understand the process now. Your PR looks good and I'm going to go ahead and merge it. Thanks for your help!

**Pull request merged**
