### PR TITLE
DOC-3727 Chunk the Tracking Logs file, alphabetize list of student event types

### PR DESCRIPTION
**Pull request by catong**
## [DOC-3727](https://openedx.atlassian.net/browse/DOC-3727)

Chunk the Tracking Logs file, alphabetize list of student event types. Updates to the Course Team event types will be done in a separate PR.

### Date Needed: ASAP

Need to merge this PR prior to documenting a new student event.

### Reviewers
- [x] Doc team review (sanity check): @edx/doc

FYI @stroilova @robrap 

### HTML Version
- [x] http://draft-researchguide-cleanup.readthedocs.io/en/latest/internal_data_formats/tracking_logs/student_event_types.html

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

### Post-review
- [x] Squash commits

### CODE REVIEW

**Comment by srpearce** [comment]
👍

**Comment by catong** [comment]
Merging https://github.com/edx/edx-documentation/pull/1548

**Comment by robrap** [comment]
@catong Thanks. Just curious why the special exam deletion happened as part of this PR?

**Comment by catong** [comment]
@robrap That was part of the clean-up/re-org. The special exam files were used in "include" directives in the main file. When I chunked tracking_logs.rst into shorter files, I moved the special exam content into the student and course team event files, and deleted the now obsolete "include" files. The replacement is not obvious because Github collapsed the files with very large diffs. Thanks for the careful review!

**Pull request merged**
