### PR TITLE
DOC: B&R Guide restructuring 2

### PR DESCRIPTION
**Pull request by catong**
This PR adds or moves the following new folders to the top level in shared and guide directories:
course_assets, course_components, course_features, developing_course, edit_course, grading, manage_live_course, rerun_course, releasing_course
Also moved are all images files to shared/images (previously in various individual subdirectories).
All relative image links fixed.

One additional change was made to create a separate OLX version of "test experiment groups" topic that cross-references the partner topic rather than trying to share a source file. Sharing a source file did not work because different file structures in the OLX Guide vs Partners and Open edX B&R did not permit the same relative paths.

@lamagnifica run_tests.sh is clean for me. Can you please do a sanity check/verification? Thanks.

### CODE REVIEW

**Comment by lamagnifica** [comment]
:+1:

**Comment by lamagnifica** [comment]
@catong the test ran without error and the OLX guide looks great. I still don't see a file to include content_experiments_test.rst in either the course_authors or open_edx_course_authors directories or index.rst files, however.

**Comment by catong** [comment]
@lamagnifica The output of each of the B&R guides includes a topic called Testing Content Experiments, but the file is actually called content_experiments_view.rst (not ...test.rst as it is in the OLX directory). Tricksy!

**Comment by catong** [comment]
Merging https://github.com/edx/edx-documentation/pull/692

**Pull request merged**
