### PR TITLE
Updates workflow for setting up timed, proctored, and practice exams

### PR DESCRIPTION
**Pull request by lamagnifica**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
## [DOC-2750](https://openedx.atlassian.net/browse/DOC-2750)

The UI for timed, proctored, and practice exams moved on, and the docs got left behind. Updates procedures for all three, and makes the wording parallel including adding some xrefs that there wasn't time for before. 
FYI I standardized the wording based on the timed exams topic, so that might be the best place to start your review. 
Also updates one image, and eliminates two that seemed less useful or more likely to go out of date.

### Date Needed

Bug fix, as soon as feasible.

### Reviewers

Possible roles follow. PR submitter checks the boxes after each reviewer
finishes and gives :+1:. 
- [x] Subject matter expert: @mushtaqak 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check for a bug fix): @catong @pdesjardins @srpearce 
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: @douglashall I think you did a lot of work on these special exams...

### Testing
- [x] Ran ./run_tests.sh without warnings or errors

### Post-review
- [x] Squash commits

**Comment by douglashall** [comment]
:+1:  Content looks good to me.

**Comment by mushtaqak** [comment]
Content looks good to me :+1:

**Comment by catong** [comment]
LGTM :+1:

**Pull request merged**
