### PR TITLE
Describe the forum migration applied during the Dogwood upgrade

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
# PR Cover Letter
- [ ] A detailed description of the changes in the body of the PR
- [ ] If available, a link to the relevant JIRA ticket in the body of the PR
  - `[PROJ-XXXX](https://openedx.atlassian.net/browse/PROJ-XXXX)`

# Sandbox
- [ ] Build a sandbox for your branch and add a link here

# Testing
- [ ] i18n
- [ ] RTL
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Analytics
- [ ] Performance
- [ ] Database migrations are backwards-compatible

# Reviewers

If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review #1
- [ ] Code review #2
- [ ] UI strings/error msgs review
- [ ] UX review
- [ ] Accessibility review
- [ ] Product review

# DevOps assistance

If it's needed, or even if you suspect it might be needed, do any/all these things as early as possible. Don't surprise devops right before merging! For example, touching envs/aws.py or or envs/common.py are dead giveaways that you'll need assistance when pushing your changes out. Things that require devops attention include, but are not limited to:
- configuration changes
- feature flags
- migrations
  Ways to get devops attention, pick-and-choose whichever is most appropriate for your specific PR:
- [ ] Tag devops on your PR (`@edx/devops`), either for review (more specific to devops = better) or just a general FYI
- [ ] File a support ticket

FYI: Tag anyone who might be interested in this PR here.

# Post-review
- [ ] Squash commits

**Comment by nedbat** [comment]
@dianakhuang @lamagnifica

**Comment by lamagnifica** [comment]
I'd like to talk about info we provide on the wiki (requires user account) vs. info we provide in our public RTD and edx-documentation repos. Is there a reason we wouldn't move @dianakhuang 's migration info from the wiki page to the installation guide? We don't have a strategy for making those decisions now, but it sure would be helpful for the doc team to develop one...)

**Comment by lamagnifica** [comment]
this should work fine as set  up now :+1: , philosophical discussion notwithstanding!

**Pull request merged**
