### PR TITLE
Use a shorter and better download command

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
This command is shorter and better.  Don't you think? @gsong @cpennington @feanil

**Comment by feanil** [comment]
:+1:

**Comment by cpennington** [comment]
:+1:

Would it be crazy to use a link-shortener or something to make the url even easier?

**Comment by feanil** [comment]
It would make it less clear what you're getting but it would make it easier for us to get analytics on how often and from where people are downloading this file.

**Comment by nedbat** [comment]
I like Feanil's idea: use files with short URLs in S3.  Each file could be a script customized to install a particular configuration and version.

**Pull request merged**
