### PR TITLE
Add myself to authors

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

Add a description of your changes.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give
reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. PR submitter checks the boxes after each reviewer
finishes and gives :+1:. 
- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check/copy edit/dev edit): 
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing
- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)
- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)
- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review
- [ ] Add description to release notes task as a comment
- [ ] Squash commits

**Comment by nedbat** [comment]
@lamagnifica @catong how's this? :)

**Comment by catong** [comment]
@nedbat. Beautiful!

**Comment by lamagnifica** [comment]
:+1:

**Pull request merged**
