### PR TITLE
docs: Added limited staff role

### PR DESCRIPTION
**Pull request by bpedx**
Add a description of your changes with links to any relevant material.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:.

- [ ] Subject matter expert:
- [ ] Subject matter expert:
- [ ] Product review:
- [ ] Partner support:
- [ ] PM review:

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @bpedx!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by adding a comment here that you have signed it.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by mphilbrick211** [comment]
Hi @bpedx! Thanks for this contribution. Are you a 2U/edX employee? If so, you'll need to be added to their entity CLA (have your manager reach out to [oscm@axim.org](oscm@axim.org). If you're contributing as an individual, you'll need to fill out the individual CLA as indicated above.

**Comment by bpedx** [comment]
Hi Michelle,

It’s Ben Piscopo on the 2U Product team. Ned B and Jeremy R both submitted
info for me today.

Do you mind also checking for me under ***@***.*** ?

Thanks,
Ben

**Comment by feanil** [comment]
FYI, I just updated Ben's records so the CLA bot should update overnight tonight.

**Comment by mphilbrick211** [comment]
> FYI, I just updated Ben's records so the CLA bot should update overnight tonight.

Thanks, @feanil! FYI @bpedx

**Comment by feanil** [comment]
No, you are covered by the 2U Entity Agreement.

**Comment by bpedx** [comment]
Nevermind, the checklist just updated itself... but now "this branch is out-of-date with the base branch". Should I Update Branch or should I Update with Rebase? @feanil

**Comment by mphilbrick211** [comment]
Hi @bpedx! Rebasing should fix it.

**Review by feanil — APPROVED** [review]

**Pull request merged**
