### PR TITLE
openassessment event titles

### PR DESCRIPTION
**Pull request by clankjak**
openassessment.create_submission
openassessment.save_submission
openassessment.student_training_assess_example
openassessment.upload_file

should be openassessmentblock

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @clankjak! I've created [OSPR-765](https://openedx.atlassian.net/browse/OSPR-765) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mhoeber** [comment]
@lamagnifica   see event changes

**Comment by lamagnifica** [comment]
@clankjak, thank you for this contribution!
@stroilova would you please double check me on this? I looked at a log file and was able to verify the correction to the names of two event types, "openassessmentblock.create_submission" and "openassessmentblock.save_submission". However, I continue to see "openassessment.student_training_assess_example" events in logs (no "block"). I was not able to locate an "upload_file" event to confirm that event name.

**Comment by sarina** [comment]
@clankjak could you please confirm you've sent in your contributor's agreement?

Also please add yourself to the AUTHORS file in this repo. Thanks!

**Comment by sarina** [comment]
@clankjak got your contributor's agreement, thanks!

@mhoeber this is good to go from IP perspective.

**Comment by clankjak** [comment]
If it's helpful - for 15390x series courses (entrepreneurship 1

**Comment by clankjak** [comment]
If it's helpful - for mit 15390x series courses (entrepreneurship 101, 102) I'm also only seeing openassessmentblock for create and save submission, though we don't have a student training component in our assessments, or file uploads.

**Comment by stroilova** [comment]
Thanks @clankjak  and @lamagnifica  , I'm seeing the following event_types  in the event logs recently:

openassessmentblock.submit_feedback_on_assessments
openassessmentblock.self_assess 
openassessmentblock.save_submission 
openassessmentblock.peer_assess 
openassessmentblock.get_peer_submission 
openassessmentblock.create_submission  
openassessment.upload_file
openassessment.student_training_assess_example

So it looks like save and create submission use openassessmentblock, while the last two are openassessment.\* , as in the original documentation.

**Comment by sarina** [comment]
@clankjak ^ can you respond to the above feedback?

**Comment by clankjak** [comment]
@sarina @lamagnifica Pulled all the openassessment event types from our datasets:
openassessment

openassessment.upload_file
openassessmentblock.create_submission
openassessmentblock.get_peer_submission
openassessmentblock.peer_assess
openassessmentblock.save_submission
openassessmentblock.self_assess
openassessmentblock.submit_feedback_on_assessments

Which is exactly the same as yours, @stroilova; though I can't confirm for student_training_assess_example since we don't have it in our courses.

**Comment by lamagnifica** [comment]
thank you @clankjak. Please let me know if you want to add a separate commit to this PR, or if you'd like me to make the necessary corrections to the research guide.

**Comment by clankjak** [comment]
@lamagnifica I'm totally new to GitHub, so I'm concerned I might make a mistake - it might be best if you handle it. Thanks!

**Comment by lamagnifica** [comment]
sure, no problem @clankjak. I will create a new PR and tag you on it.

**Pull request closed without merging**
