### PR TITLE
Ahodges/relnotes 20151007

### PR DESCRIPTION
**Pull request by lamagnifica**
@mhoeber

### CODE REVIEW

**Comment by mhoeber** [comment]
:+1:  thanks

**Comment by lamagnifica** [comment]
@mhoeber @shnayder @dsjen @dan-f please sanity check for images and mentions of video preview in insights_1007_2015.rst (and comments welcome on anything else)

**Comment by mhoeber** [comment]
:+1:

**Comment by dan-f** [comment]
:+1:

**Pull request merged**
