### PR TITLE
Update for new WYSIWYG editor for ORA prompts

### PR DESCRIPTION
**Pull request by srpearce**
## [DOC-3851](https://openedx.atlassian.net/browse/DOC-3851)

Update course author documentation to reflect the new WYSIWYG editor for ORA prompts.

### Date Needed (optional)

22 December 2017

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [x] Subject matter expert: @bill-filler 
- [ ] Doc team review (copy edit?): @edx/doc
- [ ] Partner support: @jaakana
- [ ] PM review: @mmacfarlane

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Review by grantgoodmanedX — APPROVED** [review]
👍  Looks good. But note that the OSPR seems to be up for some significant refactoring (which I don't think will affect the doc, but may affect the timing of the release).

**Comment by srpearce** [comment]
@grantgoodmanedX Yeah, I was assuming a best-case scenario and wanted to have docs ready just in case it does release soon. Better early than late!

**Comment by JAAkana** [comment]
(👍 )

**Comment by srpearce** [comment]
@bill-filler Please confirm that these doc changes reflect [the new PR for this feature](https://github.com/edx/edx-ora2/pull/1088). Thanks!

**Comment by bill-filler** [comment]
@srpearce 
looks good, thank you

**Pull request merged**
