### PR TITLE
added dynamically generated copyright year

### PR DESCRIPTION
**Pull request by shailysangwan**
https://openedx.atlassian.net/browse/DOC-3212
with reference to the [outreachy page](https://openedx.atlassian.net/wiki/display/COMM/Outreachy+Round+13)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @akanksham03! I've created [OSPR-1436](https://openedx.atlassian.net/browse/OSPR-1436) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by shaunagm** [comment]
@lamagnifica

(Also, @shailysangwan, your agreement has been processed.)

**Comment by lamagnifica** [comment]
Hi @shailysangwan in addition to the automated tests, please also test out your changes locally. This gives you a chance to look at the rendered HTML and make sure that the result is what you expect. 
In this repo, we have a script to build numerous guides.
In a command prompt, go to the edx-documentation directory.
Enter the following command: ./run_tests.sh
(It takes a while) There will be a "build" directory inside most of the directories that you find under "en_us", for example, course_authors, open_edx_students. Open a few up to make sure the results are as expected.

**Comment by shailysangwan** [comment]
@lamagnifica I've built the HTML, and the built pages remain the same as they were before. I guess this is the expected behavior, since I only changed the state of the copyright year from static to dynamic.

I had a question though.
I was looking at `en_us/ORA2/source/conf.py`, and if I changed the copyright text to something other than edX Inc, the docs reflected that change, but if I deleted the copyright line, it still stayed there in the built page.
I tried changing some other `conf.py` files to see what was causing this, and it seems that the configuration file in `en_us/shared` is like a parent to all other configuration files with any matching options set in the configuration files at a lower level overriding those set in `shared/config.py`.
I'm just making a guess here, please confirm if this is the case.

If so, why are we adding the copyright separately in each of the `config.py` files?

**Comment by shaunagm** [comment]
Hi @shailysangwan!  You can keep this issue open and make changes here rather than opening up a new pull request -- in fact, we very strongly prefer it.  If you need help updating your PRs on Github just ping me on Slack and I'll walk you through the process.

**Comment by shaunagm** [comment]
This PR gets my :thumbsup:, although it still needs review from a member of the docs team.   I built the new docs and checked out a few different pages, and everything looks good.  Two warnings on the build ("SFD_instructor_dash_help.rst isn't included in a toctree", just for reference) but they seem unrelated to this PR.

**Comment by lamagnifica** [comment]
The "SFD_instructor_dash_help.rst isn't included in a toctree" errors were introduced by a workaround for another issue. No need to delay this merge.
Thanks for finding a more elegant solution, @shailysangwan . 👍

**Pull request merged**
