### PR TITLE
DOC-3688 SFD: Additional way of selecting site language

### PR DESCRIPTION
**Pull request by catong**
## [DOC-3688](https://openedx.atlassian.net/browse/DOC-3688)

Learners now have an additional way to change the edX site language: the language selector in the footer of every page. NB the Drupal site is available in fewer languages than the rest of the site - learners need to be made aware that the number of languages available for selection differs depending on where they are in the site, and the reason that some pages might display in English even if they have selected another language, is that not all languages are supported on all pages.

- Add this information in 2 places: 
1) "Updating Account Information" topic
2) "Welcome" topic

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [x] Doc team review: @edx/doc
- [x] Product review: @jasperho

FYI: @dhixonedx
 
### HTML Version for Reviewers
- [x] Creating an edX Account/Getting Started:
http://draftsfd-languageselector.readthedocs.io/en/latest/SFD_account.html#change-the-language-of-the-edx-org-site

- [x] Updating Your Account Info: 
http://draftsfd-languageselector.readthedocs.io/en/latest/SFD_update_acct_settings.html#choose-the-language-for-the-site

### Testing
- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [x] Squash commits

### CODE REVIEW

**Comment by jasperho** [comment]
Looks good to me! :+1:

**Comment by grantgoodmanedX** [comment]
It looks good to me, too. 👍

**Comment by catong** [comment]
Checks failing - seem to be related to changed/new links not yet merged from Publisher work.

**Comment by catong** [comment]
Merging https://github.com/edx/edx-documentation/pull/1517

**Pull request merged**
