### PR TITLE
Delete redundant file and bring deps up to date

### PR DESCRIPTION
**Pull request by timmc-edx**
- Bump `pip-tools` to be compatible with current pip, and run `make upgrade`
- Delete `run_tests`, which appears to be an accidental, and now-outdated copy of `run_tests.sh`

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

### CODE REVIEW

**Review by dianakhuang — APPROVED** [review]

**Comment by dianakhuang** [comment]
Whoops, it looks like this repo isn't running travis in Python 3.

**Comment by timmc-edx** [comment]
Should I go ahead and bump the Travis config to 3.5?

**Comment by dianakhuang** [comment]
I would say yes.

**Comment by dianakhuang** [comment]
Already approved but 👍 for moving this onto 3.5.

**Pull request merged**
