### PR TITLE
Add a checklist for product owners

### PR DESCRIPTION
**Pull request by nedbat**
Add a checklist for product owners to help them involve all appropriate parties early in the process.
### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 
- [x] Subject matter expert: @gsong
- [ ] Subject matter expert: @shaunagm 
- [ ] Subject matter expert: @jbarciauskas 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review: @marcotuts 
- [ ] Ran ./run_tests.sh without warnings or errors
### Post-review
- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by jbarciauskas** [comment]
@nedbat do we think that these questions cover everything? Are there others we aren't thinking of?

**Comment by shaunagm** [comment]
:+1:

**Comment by nedbat** [comment]
@jbarciauskas i put in what I could think of, and tagged Marco to try to get other ideas.

**Comment by lamagnifica** [comment]
👍

**Pull request merged**
