### PR TITLE
Fixes DOC-3357

### PR DESCRIPTION
**Pull request by lamagnifica**
## [DOC-3357](https://openedx.atlassian.net/browse/DOC-3357)

To address the feedback that someone working in Studio has no way to know that they can only access their dashboard from the LMS, I split our shared file into two shared files, and inserted a sentence about viewing your live course in the two guides for course teams.
### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 
- [ ] Subject matter expert: @catong 
- [x] Subject matter expert: @srpearce 
### Testing

I suggest syncing to this branch locally and building so that you can see that it works in all 4 guides.
- [ ] Ran ./run_tests.sh without warnings or errors
### Post-review
- [ ] Squash commits

### CODE REVIEW

**Comment by lamagnifica** [comment]
@stroilova FYI

**Comment by stroilova** [comment]
Thanks for the FYI @lamagnifica  very clear doc by the way :)

**Comment by srpearce** [comment]
All four guides built OK. My only suggestion (not imperative) is to make the new text a note to make it easier to see. 👍

**Comment by lamagnifica** [comment]
@catong I am going to go ahead and merge this.

**Pull request merged**
