### PR TITLE
Update docs to reflect removal of Scored field in randomized content blocks

### PR DESCRIPTION
**Pull request by srpearce**
## [DOC-3401](https://openedx.atlassian.net/browse/DOC-3401)

Delete info about **Scored** field from randomized content blocks documentation.

Also delete unnecessary screen shot.
### Date Needed (optional)

12 Oct 2016
### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 
- [ ] Subject matter expert: @sanfordstudent 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
### Testing
- [ ] Ran ./run_tests.sh without warnings or errors
### Post-review
- [ ] Squash commits

### CODE REVIEW

**Comment by sanfordstudent** [comment]
It looks like a screenshot was removed. I'm guessing it contained the Scored field. Do you need a replacement screenshot that shows a problem type dropdown menu without depicting the Scored option?

**Comment by srpearce** [comment]
@sanfordstudent Nope, that screenshot didn't show the **Scored** field. We're just in the habit of removing unnecessary screen shots when we run across them. No action required on your part :-)

**Comment by sanfordstudent** [comment]
Sounds good!

**Review by sanfordstudent — APPROVED** [review]
👍

**Comment by catong** [comment]
👍  And an extra 👍 for removing the unnecessary screenshot.

**Pull request merged**
