### PR TITLE
replaced example XML with something that will not throw an error if copy...

### PR DESCRIPTION
**Pull request by Lyla-Fischer**
...-pasted into studio

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Lyla-Fischer! I've created [OSPR-388](https://openedx.atlassian.net/browse/OSPR-388) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by sarina** [comment]
Hey Lyla! Thanks for the PR, and sorry our bot hit a bug and didn't post sooner. 

We don't have a record of you having a contributor's agreement with us - we need you to sign one as an individual contributor before we can proceed. See the bot's instructions, and we'll follow up once Jennifer has received that.

**Comment by sarina** [comment]
@Lyla-Fischer thanks, we got your agreement! (since you own your own contributions right now, it's important that you license us to receive your changes)

@mhoeber - FYI. OSPR ticket is in your team's backlog.

**Comment by mhoeber** [comment]
@Lyla-Fischer  Thank you.  I moved this to new branch and PR 151 so I could edit and add change logs.

Closing this PR

**Pull request closed without merging**
