### PR TITLE
Remove usernames as Unicode use example

### PR DESCRIPTION
**Pull request by catong**
Amendment to https://github.com/edx/edx-documentation/pull/45
Turns out we do not support Unicode characters in usernames, though we still require UTF-8 encoded CSV files. This change removes "for example, usernames" in the "Creating a Unicode-encoded CSV File" topic so that we don't seem to imply that we support usernames with Unicode characters.
@explorerleslie @dan-f @lamagnifica please give thumbs if OK. I'd like to merge this today. Thanks!
FYI @WatsonEmily

### CODE REVIEW

**Comment by dan-f** [comment]
:+1:

**Comment by explorerleslie** [comment]
:+1:

**Comment by lamagnifica** [comment]
:+1:

**Comment by catong** [comment]
Merged https://github.com/edx/edx-documentation/pull/65

**Pull request merged**
