### PR TITLE
DOC-3752: Remove ManageCourseFees file from Open edX Building and Running guide

### PR DESCRIPTION
**Pull request by catong**
## [DOC-3752](https://openedx.atlassian.net/browse/DOC-3752)

Remove the "Manage Course Fees" section from the B&R Guide - it refers to the obsolete "E-Commerce" section of the LMS Instructor Dashboard.

Verify that replacement content exists in the ICR Guide. Missing content will be added in a separate PR.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 
- [x] Subject matter expert: @mjfrey 
- [x] Doc team review (sanity check): @edx/doc

FYI: @dabdul-hathi

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Review by grantgoodmanedX — APPROVED** [review]
Looks sane, and we have corresponding info in the ICR guide ch. 6. 👍

**Comment by mjfrey** [comment]
Do we want to add a link to the new Otto based documentation?

**Comment by catong** [comment]
@mjfrey Are you referring to some Otto-based documentation that currently exists (in the ecommerce repo)? My plan was to remove this obsolete info immediately from the "Building and Running an Open edX Course" then follow up to make sure the content in the "Installing, Configuring, and Running the Open edX Platform" is brought up to date. I think that's the better location for any Otto doc, do you agree?

**Review by mjfrey — APPROVED** [review]

**Comment by catong** [comment]
Merging https://github.com/edx/edx-documentation/pull/1578

**Pull request merged**
