### PR TITLE
Fixes DOC-1194, spurious speed field for events

### PR DESCRIPTION
**Pull request by lamagnifica**
@stroilova for your JIRA item. @mulby please confirm. @mhoeber , @catong , @srpearce one row removed from a table.

### CODE REVIEW

**Comment by lamagnifica** [comment]
@stroilova ,  @mulby , @mhoeber , @catong , @srpearce

**Comment by mhoeber** [comment]
:+1:

**Comment by catong** [comment]
:+1:

**Comment by mulby** [comment]
:+1:

**Comment by stroilova** [comment]
sorry for late response, but :+1:  also

**Pull request merged**
