### PR TITLE
docs: added notification doc for course author and open edx student

### PR DESCRIPTION
**Pull request by sundasnoreen12**
[INF-1017](https://2u-internal.atlassian.net/browse/INF-1017)

**Description**
I added section Managing Notifications in both **course_authors** and **open_edx_students**

The content of this section is presented in this doc: https://docs.google.com/document/d/1xNtDBQWqiKe0H_iukkN7hr77Evljs3Zn4Fc-ZXBUM-g/edit - Connect your Google account 

### Testing

- [ ] By running command make html in respective folder

### CODE REVIEW

**Review by feanil — CHANGES_REQUESTED** [review]
Please update all heading styles to match the current documentation standard: https://docs.openedx.org/en/latest/documentors/references/quick_reference_rst.html#headings

**Comment by sundasnoreen12** [comment]
> Please update all heading styles to match the current documentation standard: https://docs.openedx.org/en/latest/documentors/references/quick_reference_rst.html#headings

**Comment by sundasnoreen12** [comment]
> Please update all heading styles to match the current documentation standard: https://docs.openedx.org/en/latest/documentors/references/quick_reference_rst.html#headings

Could you please provide an example of what the desired format should be? I'm seeking assistance from the reference document titled "en_us/open_edx_students/source/SFD_notes.rst".

instead of 
########
Heading 1
########

should i use this
Heading 1
########

**Review by awais-ansari — APPROVED** [review]

**Comment by sundasnoreen12** [comment]
@feanil i created a duplicate PR because we need to merge the documentation related work created in this PR to enable product tour for notification on production. if I'm missing something, I'll fix that in this opened PR. 

Duplicate PR link is here: https://github.com/openedx/edx-documentation/pull/2176

**Comment by feanil** [comment]
It looks like you fixed the thing I requested in the duplicate PR so I think this is fine to close.  Out of curiousity, how is this page being used in the product tour?  Are you linking from the notifications code to these published pages in some way?  Should there be comments here so that we can understand the impact of removing or renaming these pages in the future?

**Comment by awais-ansari** [comment]
> It looks like you fixed the thing I requested in the duplicate PR so I think this is fine to close. Out of curiousity, how is this page being used in the product tour? Are you linking from the notifications code to these published pages in some way? Should there be comments here so that we can understand the impact of removing or renaming these pages in the future?

Screenshot 2023-09-05 at 4 18 15 PM

**Comment by awais-ansari** [comment]
Its a duplicate PR. https://github.com/openedx/edx-documentation/pull/2176

**Pull request closed without merging**
