### PR TITLE
Rewords references to Open edX releases

### PR DESCRIPTION
**Pull request by lamagnifica**
@jbarciauskas @mhoeber please take a look. I did not change any references to commands or file locations (save the wiki page), only inline use of “named release”. Fixes DOC-2228.

### CODE REVIEW

**Comment by mhoeber** [comment]
:+1:  thanks

**Comment by mhoeber** [comment]
sorry didn't mean to close

**Comment by lamagnifica** [comment]
@jbarciauskas the biggest changes to the docs resulted from the change to the name of the wiki page.

**Comment by lamagnifica** [comment]
@jbarciauskas if you can give thumbs on this, all docs rebuilt tomorrow will once again have working links to the wiki page

**Comment by jbarciauskas** [comment]
:+1:

**Pull request merged**
