### PR TITLE
DOC-3397: Move Proctored Exams from under Credit

### PR DESCRIPTION
**Pull request by catong**
## [DOC-3397](https://openedx.atlassian.net/browse/DOC-3397)

This PR is one of several PRs that will update proctored exam documentation for learners.
This PR decouples the proctored exam concept from for-credit courses. In the Learner's Guide, the section on proctored exams moves from its previous place under "Receiving Academic Course Credit" to "Completing Different Types of Assignments."

I experimented with combining the "Online Proctoring Rules" into a single file with the entire rest of the proctored exam learner documentation but decided against it. The proctored exam doc is very long and the rules get lost. Even if the index for "Completing Different Types of Assignments" is not quite parallel, the information is much more findable when chunked this way.
### Reviewers
- [x] SME: @andy-armstrong 
- [ ] Product: @sstack22 or @marcotuts 
- [x] Doc team review (sanity check/copy edit/dev edit): @edx/doc 

FYI: @jaakana @jhendersonedx @dhixonedx
### Testing
- [x] Ran ./run_tests.sh without warnings or errors
### HTML Draft Version
- [x] http://draft-sfd-proctoredexams.readthedocs.io/en/latest/completing_assignments/index.html
### Post-review
- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Review by andy-armstrong — APPROVED** [review]
👍 this material works much better in its new location

**Comment by lamagnifica** [comment]
Totally 👍 on the "Taking a Proctored Exam" section. 
But... I understand your reasoning for placing the proctoring rules section at the same level as the actual "taking a proctored exam" section, but would still prefer to see it placed under the "taking a proctored exam" heading. It wouldn't have to be moved into the same file, I don't think, and it could even be in a completely different part of the guide as a reference. The list of links in the "[Completing Different Types of Assignments](http://draft-sfd-proctoredexams.readthedocs.io/en/latest/completing_assignments/index.html)" topic reads oddly now.

**Comment by catong** [comment]
@lamagnifica Yeah, I wrestled with the pros and cons of the various options. 
I definitely don't want to move the rules topic to a different part of the guide. I think it's pretty important to keep those rules as accessible as possible without making learners have to search hard. 
I wasn't crazy about the idea of creating a proctoring folder just to nest the rules topic - is that the way you see to do it? Or is there another method I'm not thinking of?

**Comment by lamagnifica** [comment]
Well, it would be a heavier lift, but right now you have an introduction in each file that could be streamlined into one introduction in an index.rst, and there are other topics that could also potentially be streamlined (like getting rid of the "Know the Rules" topic and instead just having appropriate xrefs to the rules file.) Then, logically chunked rst files at the same level under the new Taking a Proctored Exam index.rst -- preparing, taking, the rules, blah, make a lot of sense to me.
(I think you're probably planning to rewrite a bunch of the introduction anyway, since it mentions "credit" a lot, so leaving additional chucking/file reorg for a later PR makes a lot of sense.)

**Comment by catong** [comment]
Merging https://github.com/edx/edx-documentation/pull/1312

**Pull request merged**
