### PR TITLE
Fixes DOC-1709

### PR DESCRIPTION
**Pull request by lamagnifica**
@catong @srpearce I made sure that all gif files had corresponding
png's before deleting, and also searched the entire en_us file for use
of ".gif". HTML builds without errors (B&R guide)

### CODE REVIEW

**Comment by srpearce** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by catong** [comment]
@lamagnifica awesome! I second every one of @srpearce's thumbs.

**Comment by lamagnifica** [comment]
2nd commit removes unused png files, thank you @shnayder you get my cake! @srpearce would you please sync to this branch and make html for several guides? I did so for all guides and didn't get any missing file errors, but would like to be sure (I have all the deleted images in a separate file on my desktop so can easily add anything back).

**Comment by lamagnifica** [comment]
woo hoo travis didn't choke vv

**Comment by srpearce** [comment]
Ran **make html** for the student and course authors guides and the release notes and did some spot-checking. No errors in make html and everything looks great. Doubleplushuzzah!

**Pull request merged**
