### PR TITLE
changed text

### PR DESCRIPTION
**Pull request by shailysangwan**
changed "unit identifier" to "location ID".
with reference to https://github.com/edx/edx-platform/pull/13637#issuecomment-255843703

See [Update guidance in the Studio Unit Location text JIRA issue](https://openedx.atlassian.net/browse/DOC-2167).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @akanksham03! I've created [OSPR-1535](https://openedx.atlassian.net/browse/OSPR-1535) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by srpearce** [comment]
[DOC-2167](https://openedx.atlassian.net/browse/DOC-2167)

**Comment by gsong** [comment]
@edx/doc Is this PR still valid?

* [ ] Yes: what do we need to do to move this forward?
* [ ] No: go ahead and close it with a short reason.

Thank you.

**Comment by srpearce** [comment]
Superseded by [PR 14303](https://github.com/edx/edx-platform/pull/14303).

**Comment by catong** [comment]
@srpearce @gsong  Isn't this the documentation counterpart to PR 14303, which addresses the same issue in the Studio sidebar? The doc change might still need to be made.

**Comment by srpearce** [comment]
@catong Oh, damn - yes, you're right. I'll take care of this.

**Pull request merged**
