### PR TITLE
Changed readthedocs.org to readthedocs.io

### PR DESCRIPTION
**Pull request by grantgoodmanedX**
## [DOC-3574](https://openedx.atlassian.net/browse/DOC-3574)

Changed readthedocs.org to readthedocs.io in files from PR 1308 as well as 5 additional files found through search.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [x] Doc team review (sanity check): @edx/doc

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [x] Squash commits

### CODE REVIEW

**Comment by srpearce** [comment]
@grantgoodmanedX — Can you test all the links? I did a little spot-checking and found a few that were broken in one of the developer's guide files. If the link is broken, you can try to figure out what the link should be, or ask one of the developers (Dave Ormsbee might be a good start if the link is in the developer's guide).

**Comment by srpearce** [comment]
Also, I checked the build failure, and it's just because of the Python formatting problem that I just fixed. So if Travis doesn't find any more errors, you can go ahead and merge when all the links are working.

**Comment by grantgoodmanedX** [comment]
I checked for broken links and fixed the ones I found. Do we have any automated link checkers?

**Comment by srpearce** [comment]
@grantgoodmanedX Sphinx has "linkchecker"; we can run it manually by using the ``make linkchecker`` command the way we use the ``make html`` command. If you want some background information, see [PR 1267](https://github.com/edx/edx-documentation/pull/1267). (I'll also add this to our wiki since I'd forgotten about it.)

**Comment by srpearce** [comment]
@grantgoodmanedX If all the links are working, you can go ahead and merge this PR.

**Comment by grantgoodmanedX** [comment]
Running `make linkcheck` on just the B&R guide produced over 500 lines of output, a quick scan of which didn't indicate any problems with this PR.  I'll open another ticket in JIRA to check links on it and other documents.

**Pull request merged**
