### PR TITLE
Clarify usage of prereq. course subsections

### PR DESCRIPTION
**Pull request by Madsn**
It seems to me I can enable section prerequisites for a course in studio, but it will not work until course prerequisites is installed as detailed here: http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/enable_prerequisites.html

I was assuming if there was some connection between "course prerequisites" and "section prerequisites", it would be indicated in the documentation. Only place I found any indication of that being the case was here: https://openedx.atlassian.net/wiki/spaces/EDUCATOR/pages/50528923/Gating+Subsection+Gating

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Madsn! I've created [OSPR-1987](https://openedx.atlassian.net/browse/OSPR-1987) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by nedbat** [comment]
@Madsn Thanks for the improvement!  We'll need you to sign the contributor's agreement before we can merge this change.  I know it seems like a lot for a small change, but we're hoping you'll contribute more in the future :)   Let us know what you'd like to do.

**Comment by Madsn** [comment]
@nedbat Sorry for the delay. I've filled out and sent the contributor's agreement to the email specified in the document.

**Comment by nedbat** [comment]
@Madsn Thanks for your contributor agreement.

@edx/doc Take a quick look.

**Review by grantgoodmanedX — APPROVED** [review]
👍 This looks good (after resolving merge conflicts. Sorry for the long delay.

**Comment by openedx-webhooks** [comment]
@Madsn 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1613&entry.1484655318=https://github.com/Madsn&entry.752974735=2017-10-29+19:59&entry.1917517419=2018-10-16+20:17&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
