### PR TITLE
docs: flex peer ora course override

### PR DESCRIPTION
**Pull request by jansenk**
Add documentation for ORA card with link to flexible override documentation

### CODE REVIEW

**Review by leangseu-edx — CHANGES_REQUESTED** [review]
Can you make a file `ora_settings.rst` instead? We are expecting this to multiple setting maybe? And we are expecting that file https://github.com/openedx/edx-platform/blob/8780e606f70790e226115f797887ed6343a1e9b2/cms/envs/common.py#L2700.

**Comment by jansenk** [comment]
> Can you make a file `ora_settings.rst` instead? We are expecting this to multiple setting maybe?

I don't want things to be any more spread out than they are already, but I did adjust the formatting of this page. Any additional settings will also go here.

> And we are expecting that file https://github.com/openedx/edx-platform/blob/8780e606f70790e226115f797887ed6343a1e9b2/cms/envs/common.py#L2700.

Good point. I'll make sure to make that change before we release.

**Review by mattcarter — APPROVED** [review]
I'm approving, with the idea that the agreed to changes will get done.

**Review by leangseu-edx — APPROVED** [review]

**Comment by jansenk** [comment]
https://github.com/openedx/edx-platform/pull/32791

**Pull request merged**
