### PR TITLE
DOC-1807 Update install_fullstack.rst

### PR DESCRIPTION
**Pull request by gregrgay**
Updated login details for fullstack LMS, change old edx/edx login to specific users, see JIRA DOC-1807 https://openedx.atlassian.net/browse/DOC-1807

Note that this does not fix the fact that none of these users has is_superuser privileges.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @gregrgay! I've created [OSPR-495](https://openedx.atlassian.net/browse/OSPR-495) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by sarina** [comment]
Thanks @gregrgay - once we have your contributing info, and you add another commit to add yourself to AUTHORS, we'll merge this.

Instructions on superuser access can be found here: https://github.com/edx/configuration/wiki/edX-Managing-the-Full-Stack Perhaps it's worth linking to that page. I believe it is intentional that no superuser is created by default.

**Comment by sarina** [comment]
@gregrgay any updates on your contributing info?

**Comment by gregrgay** [comment]
Sent to jennifer@edx.org Apr 2.

**Comment by sarina** [comment]
@gregrgay ah my bad, apparently she's on vacation. I'll follow up with her when she's back, which I think is next week.

**Comment by sarina** [comment]
@gregrgay sorry this took so long, but everything is now straightened out. Thanks so much for contributing the fix!

**Pull request merged**
