### PR TITLE
Fix Enrollment Report Link

### PR DESCRIPTION
**Pull request by mhoeber**
@lamagnifica

### CODE REVIEW

**Comment by lamagnifica** [comment]
there were links in the change logs for both open and partner B&R that were also broken

**Comment by mhoeber** [comment]
@lamagnifica  that didn't show locally for me.  i'll look again

**Comment by mhoeber** [comment]
@lamagnifica   try building open source guide now

**Comment by lamagnifica** [comment]
Since I couldn't sync to this branch locally, I used RTD to build a draft:
http://draft-fix-links-20150909.readthedocs.org/en/latest/running_course/course_enrollment.html#report-learners-not-yet-enrolled

I checked the link in that section and in the change log.

:+1:

**Pull request merged**
