### PR TITLE
Update the documentation for Badgr integration

### PR DESCRIPTION
**Pull request by mrtmm**
Update the documentation for Badgr integration updates.

`edx-platform` PR for these changes: https://github.com/edx/edx-platform/pull/27181

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mrtmm! I've created [OSPR-5702](https://openedx.atlassian.net/browse/OSPR-5702) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@mrtmm Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward. We will review this soon.

**Comment by natabene** [comment]
@schenedx Could you please have a look?

**Review by schenedx — APPROVED** [review]
👍

**Comment by schenedx** [comment]
The documentation change here LGTM. Will merge as soon as https://github.com/edx/edx-platform/pull/27181 is merged.

**Comment by openedx-webhooks** [comment]
@mrtmm 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1927&entry.1484655318=https://github.com/mrtmm&entry.752974735=2021-03-30+08:45&entry.1917517419=2021-06-03+15:48&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
