### PR TITLE
Updates research guide for new video player controls

### PR DESCRIPTION
**Pull request by lamagnifica**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
## [DOC-2562](https://openedx.atlassian.net/browse/DOC-2562)

Updates the research guide to include the new video controls.

### Date Needed

As soon as feasible, already released.

### Reviewers

Possible roles follow. PR submitter checks the boxes after each reviewer
finishes and gives :+1:. 
- [ ] Subject matter expert: @clrux 
- [ ] Subject matter expert: @stroilova 
- [ ] Doc team review (copy edit): @pdesjardins @catong @srpearce 

### Testing
- [x] Ran ./run_tests.sh without warnings or errors

### Post-review
- [ ] Squash commits

**Comment by downzer0** [comment]
@lamagnifica I'm not sure of the event emitting with this. Would you mind giving me some time to investigate?

**Comment by lamagnifica** [comment]
@clrux not a problem. I'll also surface this to Olga.

**Comment by stroilova** [comment]
Thanks for flagging me @lamagnifica ! 

@clrux , do I understand correctly that the goal of this PR is to have both the bottom CC and side Show Transcript buttons emit the same show/hide_transcript events? 

Will researchers be able to distinguish which button caused the event to be emitted? Thanks.

**Comment by downzer0** [comment]
@stroilova It'd be ideal, I think, to track them individually. It may be nice to know when the closed-captioning _and_ the transcript are used independently. Furthermore, you can turn on closed-captioning even if the transcript is hidden.

**Comment by stroilova** [comment]
Thanks @clrux !  I sent you a note off-github to see if we can quickly chat in person.

**Comment by lamagnifica** [comment]
New design and testing in progress.

**Pull request closed without merging**
