### PR TITLE
A few corrections to analyticstack

### PR DESCRIPTION
**Pull request by iloveagent57**
...around starting the pipeline and creating a sample task.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [x] Subject matter expert: 
- [ ] Subject matter expert: 
- [x] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Review by mulby — APPROVED** [review]
LGTM - thanks for fixing this!

**Comment by catong** [comment]
@iloveagent57 Thanks for submitting this PR. I ran tests; 👍  from a Docs perspective.

**Comment by nedbat** [comment]
@iloveagent57 if these changes (or future ones) are appropriate for the Ficus version of the docs, ping me on the PR, and we can get it cherry-picked over.

**Comment by nedbat** [comment]
@iloveagent57 ps: it's also good form to delete the branches once the PR is merged.

**Pull request merged**
