### PR TITLE
Add Kyle Boots

### PR DESCRIPTION
**Pull request by indagation**
## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

Added my info to the contributors list
### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 
- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [x] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

@mmacfarlane @gsong
### Testing
- [ ] Ran ./run_tests.sh without warnings or errors
### HTML Version (optional)
- [ ] Build an RTD draft for your branch and add a link here
### Sandbox (optional)
- [ ] Point to or build a sandbox for the software change and add a link here
### Post-review
- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @indagation! I've created [OSPR-1497](https://openedx.atlassian.net/browse/OSPR-1497) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by indagation** [comment]
I am an educational technologist at MIT so I should be covered by MIT's institutional agreement with edX.

**Comment by gsong** [comment]
@indagation Yup, you're already in the list. 🙌

**Comment by indagation** [comment]
Conflicts resolved.

**Comment by nedbat** [comment]
@indagation not sure what happened here with the conflicts. I went ahead and added your name to AUTHORS separately.  Thanks!

**Pull request closed without merging**
