### PR TITLE
Added IE 11

### PR DESCRIPTION
**Pull request by lamagnifica**
@benpatterson , @mhoeber please review. 
I added IE 11 as fully supported in all three products. I kept IE9. The image that follows may be easier to read than the rst table markup.

screen shot 2015-04-15 at 2 19 20 pm

### CODE REVIEW

**Comment by mhoeber** [comment]
:+1:

**Comment by benpatterson** [comment]
Hrm, is there a reason we don't say 'provisional' like we did on the old page? @lamagnifica

**Comment by lamagnifica** [comment]
@benpatterson we certainly can -- I just understood the JIRA story as saying that we did support IE11, without the provisions...!
DOC-1871

**Comment by benpatterson** [comment]
Sorry for any confusion. My point was that IE11 should be on the list---following whatever pattern we have for the other IEs. In that case, we only had IEs as provisional in all cases, unless I was missing some other piece of documentation...

**Comment by lamagnifica** [comment]
Revisions made:
screen shot 2015-04-15 at 3 51 21 pm

**Comment by benpatterson** [comment]
:+1:

**Comment by lamagnifica** [comment]
@benpatterson for comparison, this is what we currently state:
http://edx.readthedocs.org/projects/edx-release-notes/en/latest/front_matter/browsers.html
Note that we currently say that we support IE 9 and 10 for the LMS, but provisionally support them for Studio and Insights. Please let me know if that is not accurate.

**Pull request merged**
