### PR TITLE
Committing ICR guide reorganization done by spearce for DOC-2240

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
@pdesjardins @srpearce look ok?  There were conflicts, but they were really easy to resolve, not sure why git even considered them conflicts.

**Comment by pdesjardins** [comment]
@nedbat This looks good. I'm wondering why there are 40 changed files in your PR and there were 39 changed files in mine. Did you add one?

**Comment by pdesjardins** [comment]
I visually compared the files in the list. I didn't find the difference. Maybe git is counting some of the renamed files differently? :+1:

**Comment by nedbat** [comment]
Looks like your PR has "install_devstack.rst" as a rename (1 file changed) and mine has it as a delete and add (2 files changed).  More of git being a little weird about this.

**Comment by nedbat** [comment]
@pdesjardins @lamagnifica @srpearce ok?

**Comment by pdesjardins** [comment]
This PR looked good to me. Thanks for explaining the different number of file changes. :+1:

**Pull request merged**
