### PR TITLE
doc: Explains the conditionals for weekly learning goals to successfully send 

### PR DESCRIPTION
**Pull request by DeanJayMathew**
I just added more context to the instructions, clearly stating the five conditions that the script checks in order for an email to be sent or not.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:.

- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc @sarina 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @DeanJayMathew!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by feanil** [comment]
@DeanJayMathew change looks great, let me know once you've signed the CLA.

**Comment by sarina** [comment]
@DeanJayMathew sorry I missed the original ping! Thanks for the addition. 

@feanil I'm in Salesforce and Dean is covered by an Entity CLA. Let's figure this out offline.

**Comment by sarina** [comment]
@DeanJayMathew that was quick! I fixed our data (you are covered for CLA), but it'll take until tonight for the data to make its way to our automation.

In the meantime, one last thing you have to do is reword your commit message, in two ways: it needs to be more descriptive, and it needs to start with `doc:` (see https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html)

How about, `doc: Explain how to enable weekly learning goals`?

I'm not sure how to do this from the GitHub GUI. If you'd like, I can make the change for you - just give me the final wording you'd like to use.

**Comment by DeanJayMathew** [comment]
Hi @sarina and @feanil, thanks!

I reworded it at the top of this page to be:
doc: Explains the conditionals for weekly learning goals to successfully send

Have I done it correctly?

**Comment by feanil** [comment]
@DeanJayMathew unfortunately the PR title is not the same as the commit message.  It's the commit message that needs to change.  I've gone ahead and done that for you here.  But if you're curious about how to do it, you can take a look at [the docs here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message).

**Comment by feanil** [comment]
Also @DeanJayMathew does this change need to be ported to master as well?

**Comment by feanil** [comment]
Looks like they do, so I cherry-picked them to master in this PR: https://github.com/openedx/edx-documentation/pull/2103

**Comment by openedx-webhooks** [comment]
@DeanJayMathew 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-documentation&entry.867055334=https://github.com/openedx/edx-documentation/pull/2102&entry.1484655318=https://github.com/DeanJayMathew&entry.752974735=2023-02-04+01:34&entry.1917517419=2023-02-08+14:41&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by DeanJayMathew** [comment]
Thank you @feanil !

**Pull request merged**
