### PR TITLE
Delete Learner Engagement Report

### PR DESCRIPTION
**Pull request by OmarIthawi**
I don't think this report exists. By taking a loot at https://github.com/edx/edx-documentation/pull/92 , it seems more like hack done for specific edX partners.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: `@mhoeber` (who's no longer at edX as far as I know)
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-2754](https://openedx.atlassian.net/browse/OSPR-2754) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@OmarIthawi  Thank you for your contribution. @marcotuts Can you have a look at this?

**Comment by OmarIthawi** [comment]
Thanks @natabene and @marcotuts!

Please take this pull request with a grain of salt. I'm happy to be educated and learn this this feature exists. It however, doesn't seem like an actual core feature.

**Comment by OmarIthawi** [comment]
@natabene We still haven't gotten a review for this PR. I'm closing this. Probably won't get to it in the near future, would be happy if someone took over.

**Comment by openedx-webhooks** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1747&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2018-10-31+11:39&entry.1917517419=2018-12-03+10:36&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
