### PR TITLE
added shellyu@mit.edu

### PR DESCRIPTION
**Pull request by shellyu**
Added my info to the contributors list
### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 
- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [x] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

@mmacfarlane @gsong 
### Post-review
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @shellyu! I've created [OSPR-1496](https://openedx.atlassian.net/browse/OSPR-1496) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by gsong** [comment]
@shellyu Thank you for your PR. We appreciate you taking the time to make the contribution.

Please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can review this pull request. We realize it's additional work for a simple change in this case, but you only have to do this _once_ and we're hoping you would make future contributions as well.

**Comment by lamagnifica** [comment]
👍

**Comment by shellyu** [comment]
Hi @gsong! Shira and I should be covered by MIT's institutional agreement with edX. Do you need any more info from us about that?

@pdpinch @sfrucht

**Comment by gsong** [comment]
@shellyu Nope. I'll add you to the list of contributors. Thanks for pointing that out.

**Comment by gsong** [comment]
@shellyu Another merged PR has caused a conflict in your branch, can you resolve the conflict, please? Thank you.

**Comment by shellyu** [comment]
@gsong I resolved the conflict

**Pull request merged**
