### PR TITLE
docs: add 'Palm' to titles

### PR DESCRIPTION
**Pull request by mtyaka**
This adds "Palm Release" to titles in the open-release/palm.master branch as instructed by the release instructions:
https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#5.-Update-the-documentation

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mtyaka!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mtyaka** [comment]
@kdmccormick Can you review?

**Comment by mtyaka** [comment]
After this is merged someone with access to readthedocs.org will have to perform the steps related to readthedocs.org in https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#5.-Update-the-documentation

**Review by kdmccormick — APPROVED** [review]
Looks good.

> After this is merged someone with access to readthedocs.org will have to perform the steps related to readthedocs.org in https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#5.-Update-the-documentation

On it.

**Comment by openedx-webhooks** [comment]
@mtyaka 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-documentation&entry.867055334=https://github.com/openedx/edx-documentation/pull/2133&entry.1484655318=https://github.com/mtyaka&entry.752974735=2023-04-12+08:22&entry.1917517419=2023-04-13+18:22&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by kdmccormick** [comment]
Results:

https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/open-release-palm.master/

https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/open-release-palm.master/

https://edx.readthedocs.io/projects/open-edx-learner-guide/en/open-release-palm.master/

**Pull request merged**
