### PR TITLE
Fix typo in run_xsscommitlint.

### PR DESCRIPTION
**Pull request by robrap**
## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

Fix minor typo.

FYI: @cahrens 

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by robrap** [comment]
@grantgoodmanedX: Do you need a ticket for something this minor?

**Comment by cahrens** [comment]
👍

**Review by grantgoodmanedX — APPROVED** [review]
That's good. 👍

**Comment by grantgoodmanedX** [comment]
No, @robrap we don't need a DOC ticket for something this small. Thanks!

**Pull request merged**
