### PR TITLE
Update Flex Grading Feature

### PR DESCRIPTION
**Pull request by Daniel-hershel**
Updating the entry on flexible peer grade averaging to reflect our upcoming release of the feature to set flexible peer grading at the course level

Add a description of your changes with links to any relevant material.

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:.

- [ ] Subject matter expert:
- [ ] Subject matter expert:
- [ ] Product review:
- [ ] Partner support:
- [ ] PM review:

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Daniel-hershel!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by mphilbrick211** [comment]
Hi @Daniel-hershel! Looks like the CLA check is failing. Could you please ask your manager to reach out to oscm@axim.org and ask that you be added to the edX/2U entity CLA? Thanks!

**Comment by jansenk** [comment]
We're gonna need to wait for new screenshots for this after our meeting today

**Review by jansenk — CHANGES_REQUESTED** [review]
We're gonna need to wait for new screenshots for this after our meeting today, but other than that 👍

**Comment by mphilbrick211** [comment]
Hi @Daniel-hershel and @jansenk! Just checking in on this.

**Comment by Daniel-hershel** [comment]
Hi @mphilbrick211, my manager started this process, but we're still waiting to here back from axim about finalizing this. @jansenk we might have to remake this PR in your account if this isn't resolved this morning.

**Comment by jansenk** [comment]
I pulled these changes into https://github.com/openedx/edx-documentation/pull/2163

**Comment by openedx-webhooks** [comment]
@Daniel-hershel Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-documentation&entry.867055334=https://github.com/openedx/edx-documentation/pull/2159&entry.1484655318=https://github.com/Daniel-hershel&entry.752974735=2023-07-06+18:22&entry.1917517419=2023-07-19+14:55&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
