### PR TITLE
Prepend EDXAPP_ to ansible variables where necessary

### PR DESCRIPTION
**Pull request by sboday**
## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

Documentation for server-vars.yml comprehensive theming needs to be consistent with Configuration variables defined in ./edx_ansible/playbooks/roles/edxapp/defaults/main.yml
### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.
### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 
- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check/copy edit/dev edit): @catong @lamagnifica @pdesjardins @srpearce
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.
### Testing
- [ ] Ran ./run_tests.sh without warnings or errors
### HTML Version (optional)
- [ ] Build an RTD draft for your branch and add a link here
### Sandbox (optional)
- [ ] Point to or build a sandbox for the software change and add a link here
### Post-review
- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

Documentation for server-vars.yml comprehensive theming needs to be consistent with Configuration variables defined in
./edx_ansible/playbooks/roles/edxapp/defaults/main.yml

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @sboday! I've created [OSPR-1404](https://openedx.atlassian.net/browse/OSPR-1404) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by pdesjardins** [comment]
@sboday, our existing documentation refers to configuration property names as they appear in lms.env.json and cms.env.json. As I understand it, server_vars.yml is an optional way to set configuration properties in lms.env.json and cms.env.json. So I think it's better to refer to the underlying property names, in case someone reading the doc isn't using Ansible and server_vars.yml.

I suggest that we do not prepend EDXAPP_ to those property names, so that the documentation matches what installers will see in lms.env.json and cms.env.json.

What do you think? Am I misunderstanding? Thanks for the contribution!

**Comment by sboday** [comment]
Hi Peter,

   @pdesjardins, the issue is that the documentation page specifies
server-vars.yml values at the top and lms.env.json values at the bottom.
The page gives very precise instructions, precise enough that the reader is
tempted to cut and paste them into their files, but the property names are
wrong.  So, either the server-vars.yml instructions need to be removed, or
the property names need to be corrected.

http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/theming/activate_theme.html

Also, I would not consider server_vars.yml as optional.  Maybe starting out
in devstack that is true, but before moving to production, a well designed
project will be using server-vars.yml so that the installed software can be
recreated through automated scripts, i.e. /edx/bin/update. We should all be
encouraging developers to move their configuration from the json files to
the yml files somewhere along the development cycle. So, my personal vote
is to leave both instructions, and prepend EDXAPP_ to the server-vars.yml
section of the documentation.

Thanks to you all for supporting such an important open source project!

Stuart

**Comment by pdesjardins** [comment]
Hi, Stuart.

@sboday, thanks for clarifying. I definitely agree that making changes directly in *.env.json isn't necessarily practical in production. Also, thank you for pointing out the inconsistency. I am revising the entire theming section right now, I'm going to make sure we cover configuration in a consistent way.

I think we need to cover production-worthy configuration management (using server_vars.yml) more clearly in our installation documentation. In the documentation for specific features, which require specific property values, I prefer to refer only to the property that the server reads directly. We can refer to coverage of server_vars.yml techniques in a separate section. (Also, I'm wondering whether there might be other ways to manage configuration in production and I don't want to structure feature documentation in a way that precludes that.)

This PR has been extremely helpful in my work revising this section, thank you! I'd be happy to merge this into the doc now, it is an improvement. I do plan to excise coverage of general configuration techniques from it though.

**Comment by sboday** [comment]
@pdesjardins, I agree that the documentation will be improved when the two
configuration methods are broken out separately with clear instructions of
when to use 'devstack configuration' and when to use 'fullstack/native
configuration'. I am positive new project members are getting confused
between the two methods and when to use them.

It would be nice to cover why server-vars.yml is needed and why the
property names in the two files are not the same.

**Comment by pdesjardins** [comment]
👍

**Comment by sboday** [comment]
@pdesjardins: FYI - Here is how I tried to describe how to move from devstack to fullstack/native in a stackoverflow answer:

http://stackoverflow.com/questions/28621687/edx-platform-cannot-apply-stanford-theme

**Pull request merged**
