### PR TITLE
SOL-884 Initial write-up

### PR DESCRIPTION
**Pull request by dino-cikatic**
@srpearce this is an inital write-up of documentation for installing and enabling edX search. 
Please leave suggestions. 
(I wasn't sure should I cover ElasticSearch generally  in more detail, since it is already installed and discussions requirement)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dino-cikatic! I've created [OSPR-5347](https://openedx.atlassian.net/browse/OSPR-5347) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by dino-cikatic** [comment]
@smagoun tagging you as well to take a look.

**Comment by smagoun** [comment]
That is what we're looking for - thanks :+1: 

I suggest that someone from devops take a quick look too - @e0d can you have someone take a quick look?

**Comment by mhoeber** [comment]
@dino-cikatic   thank you.  I'm going to make a few tweaks and merge today.

**Comment by nedbat** [comment]
Hi, sorry for the new comment on this old pull request. We're testing out re-scanning contributions, and our bot added a confusing message that you can ignore. We'll fix that. Sorry about the noise.

**Pull request merged**
