### PR TITLE
Daniel/recommender

### PR DESCRIPTION
**Pull request by swdanielli**
Hi @mhoeber @pmitros ,

We just made a XBlock for collecting students' recommending resources around a problem set, and we wrote a documentation for this XBlock. Could you guys help us review the documentation?

### CODE REVIEW

**Comment by pmitros** [comment]
I made a copy/content edit, and pushed. From my point of view, :+1: now. @mhoeber

**Comment by mhoeber** [comment]
@swdanielli   thank you.  Apologize for the delay, I was sick all last week.  I will get back to you shortly on this.

**Comment by mhoeber** [comment]
@swdanielli   again sorry for the delay.  Thanks for doing this.  Can you add a section showing the XML representation of the component?  For example, like:  http://edx.readthedocs.org/projects/edx-partner-course-staff/en/latest/exercises_tools/checkbox.html#checkbox-problem-xml

**Comment by mhoeber** [comment]
@swdanielli  I'm going to merge this and follow up on xml info.

**Comment by pmitros** [comment]
@mhoeber Thanks!

**Pull request merged**
