### PR TITLE
Rename studio.yml to cms.yml

### PR DESCRIPTION
**Pull request by misilot**
Rename studio.yml to cms.yml

studio.yml was renamed to cms.yml in newer releases

### Date Needed (optional)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @misilot! I've created [OSPR-5878](https://openedx.atlassian.net/browse/OSPR-5878) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by sarina** [comment]
@misilot where was this renamed? I see plenty of references to `studio.yml` in this repo but not to `cms.yml`, and looking at https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L1085 it looks like the default config file is still `studio.yml`. I admit I don't know much about configuration but if you can point me at where this was changed that'd be great, thanks!

**Comment by misilot** [comment]
Hmm looks like you are right. Sorry, was thinking it switched from `studio.yml to `cms.yml`, but I think it was the other way around, and Tutor uses `cms` still https://github.com/overhangio/tutor/blob/e532f34909258f96e9ad3166abffd3c42fae495d/tutor/templates/apps/openedx/config/cms.env.json

Sorry about that!

**Comment by openedx-webhooks** [comment]
@misilot Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1958&entry.1484655318=https://github.com/misilot&entry.752974735=2021-06-23+00:01&entry.1917517419=2021-06-23+00:48&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
