### PR TITLE
Adds definition for "IDA" to Glossary page.

### PR DESCRIPTION
**Pull request by lsiden**
IDA is Independent Deployed Application

https://github.com/edx/edx-documentation/issues/1917

## [DOC-XXXX](https://openedx.atlassian.net/browse/DOC-XXXX)

If the release date of a feature is known or estimated, provide it to give reviewers guidance on turnaround time.

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:. 

- [ ] Subject matter expert: 
- [ ] Subject matter expert: 
- [ ] Doc team review (sanity check, copy edit, or dev edit?): @edx/doc
- [ ] Product review:
- [ ] Partner support: 
- [ ] PM review: 

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [ ] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @lsiden! I've created [OSPR-5639](https://openedx.atlassian.net/browse/OSPR-5639) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@lsiden Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by lsiden** [comment]
@natabene I am currently on-boarding with OpenCraft. When I have an opencraft.com email account, I will resubmit this PR under that account so it will then be covered by whatever agreement EdX and OpenCraft have together.

Respectfully,

**Comment by openedx-webhooks** [comment]
@lsiden Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-documentation&entry.867055334=https://github.com/edx/edx-documentation/pull/1918&entry.1484655318=https://github.com/lsiden&entry.752974735=2021-02-24+12:03&entry.1917517419=2021-02-24+18:11&entry.2133058324=No) so we can improve your experience in the future.

**Comment by natabene** [comment]
@lsiden Thanks for the explanation, got it. Once you have been onboarded, please ask Xavier to reach out to me to confirm, and I will add your Github username to our list of contributors. You then can just re-open this PR, if you wish, no need to open a new one under a different account.

**Pull request closed without merging**
