### PR TITLE
Add documentation for course authors to use the SCORM XBlock

### PR DESCRIPTION
**Pull request by graemeglass**
Add a description of your changes with links to any relevant material.

### Date Needed (optional)

1 July 2023

### Reviewers

Possible roles follow. The PR submitter checks the boxes after each reviewer finishes and gives :+1:.

- [ ] Subject matter expert:
- [ ] Subject matter expert:
- [x] Product review:
- [x] Partner support:
- [ ] PM review:

FYI: Tag anyone else who might be interested in this PR here.

### Testing

- [x] Ran ./run_tests.sh without warnings or errors

### HTML Version (optional)

- [ ] Build an RTD draft for your branch and add a link here

### Sandbox (optional)

- [ ] Point to or build a sandbox for the software change and add a link here

### Post-review

- [ ] Add a comment with the description of this change or link this PR to the next release notes task.
- [ ] Squash commits

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @graemeglass!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by jristau1984 — APPROVED** [review]
lgtm!

**Review by schenedx — APPROVED** [review]
👍

**Comment by openedx-webhooks** [comment]
@graemeglass 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-documentation&entry.867055334=https://github.com/openedx/edx-documentation/pull/2155&entry.1484655318=https://github.com/graemeglass&entry.752974735=2023-06-22+17:45&entry.1917517419=2023-06-26+11:17&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
