### PR TITLE
Fixing opaque keys reference

### PR DESCRIPTION
**Pull request by davclark**
I _think_ I specified the wiki target correctly, but please check!

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @davclark! I've created [OSPR-411](https://openedx.atlassian.net/browse/OSPR-411) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by davclark** [comment]
Please let me know if I actually need to submit a contributor agreement. Maybe easier for y'all to just make the change outside of this PR!

**Comment by sarina** [comment]
@davclark the contributor's agreement is an agreement that says that we can not only accept your intellectual property, but redistribute it. edX is licensed under the AGPL license, so by merging your work you must give us license to redistribute it. We'd love to have more people actively contributing to our documentation project, so fi you're willing to sign a contributor's agreement that'd be great!

**Comment by sarina** [comment]
@davclark - if you're unwilling or unable to sign a contributor's agreement, please do let me know. Thanks!

**Comment by davclark** [comment]
I think l may get to this later, but for a contribution of this magnitude,
(check the diff!) I'm fairly certain you could "reimplement" the change :)

I'm just in the midst of several things that need to get done right now.

D

**Comment by sarina** [comment]
@davclark of course, totally makes sense. We love to have more contributors to our documentation project, specifically, so please keep us in mind!! :)

**Pull request closed without merging**
